// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$21 {

    static final FunctionDescriptor glCompressedTexSubImage1DARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glCompressedTexSubImage1DARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glCompressedTexSubImage1DARB",
        "(IIIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glCompressedTexSubImage1DARB$FUNC, false
    );
    static final FunctionDescriptor glGetCompressedTexImageARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetCompressedTexImageARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetCompressedTexImageARB",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glGetCompressedTexImageARB$FUNC, false
    );
    static final FunctionDescriptor glLoadTransposeMatrixfARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glLoadTransposeMatrixfARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glLoadTransposeMatrixfARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glLoadTransposeMatrixfARB$FUNC, false
    );
    static final FunctionDescriptor glLoadTransposeMatrixdARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glLoadTransposeMatrixdARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glLoadTransposeMatrixdARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glLoadTransposeMatrixdARB$FUNC, false
    );
    static final FunctionDescriptor glMultTransposeMatrixfARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glMultTransposeMatrixfARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultTransposeMatrixfARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glMultTransposeMatrixfARB$FUNC, false
    );
    static final FunctionDescriptor glMultTransposeMatrixdARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glMultTransposeMatrixdARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultTransposeMatrixdARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$21.glMultTransposeMatrixdARB$FUNC, false
    );
}


