// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$27 {

    static final FunctionDescriptor glProgramLocalParameter4dvARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glProgramLocalParameter4dvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glProgramLocalParameter4dvARB",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$27.glProgramLocalParameter4dvARB$FUNC, false
    );
    static final FunctionDescriptor glProgramLocalParameter4fARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glProgramLocalParameter4fARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glProgramLocalParameter4fARB",
        "(IIFFFF)V",
        constants$27.glProgramLocalParameter4fARB$FUNC, false
    );
    static final FunctionDescriptor glProgramLocalParameter4fvARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glProgramLocalParameter4fvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glProgramLocalParameter4fvARB",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$27.glProgramLocalParameter4fvARB$FUNC, false
    );
    static final FunctionDescriptor glGetProgramEnvParameterdvARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetProgramEnvParameterdvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetProgramEnvParameterdvARB",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$27.glGetProgramEnvParameterdvARB$FUNC, false
    );
    static final FunctionDescriptor glGetProgramEnvParameterfvARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetProgramEnvParameterfvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetProgramEnvParameterfvARB",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$27.glGetProgramEnvParameterfvARB$FUNC, false
    );
    static final FunctionDescriptor glProgramEnvParameters4fvEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glProgramEnvParameters4fvEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glProgramEnvParameters4fvEXT",
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$27.glProgramEnvParameters4fvEXT$FUNC, false
    );
}


