// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$38 {

    static final FunctionDescriptor glWindowPos3dARB$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle glWindowPos3dARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3dARB",
        "(DDD)V",
        constants$38.glWindowPos3dARB$FUNC, false
    );
    static final FunctionDescriptor glWindowPos3dvARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glWindowPos3dvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3dvARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$38.glWindowPos3dvARB$FUNC, false
    );
    static final FunctionDescriptor glWindowPos3fARB$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle glWindowPos3fARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3fARB",
        "(FFF)V",
        constants$38.glWindowPos3fARB$FUNC, false
    );
    static final FunctionDescriptor glWindowPos3fvARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glWindowPos3fvARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3fvARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$38.glWindowPos3fvARB$FUNC, false
    );
    static final FunctionDescriptor glWindowPos3iARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glWindowPos3iARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3iARB",
        "(III)V",
        constants$38.glWindowPos3iARB$FUNC, false
    );
    static final FunctionDescriptor glWindowPos3ivARB$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glWindowPos3ivARB$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWindowPos3ivARB",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$38.glWindowPos3ivARB$FUNC, false
    );
}


