// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$48 {

    static final FunctionDescriptor glVertexAttribI3uiEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glVertexAttribI3uiEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI3uiEXT",
        "(IIII)V",
        constants$48.glVertexAttribI3uiEXT$FUNC, false
    );
    static final FunctionDescriptor glVertexAttribI4uiEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glVertexAttribI4uiEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI4uiEXT",
        "(IIIII)V",
        constants$48.glVertexAttribI4uiEXT$FUNC, false
    );
    static final FunctionDescriptor glVertexAttribI1ivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glVertexAttribI1ivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI1ivEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$48.glVertexAttribI1ivEXT$FUNC, false
    );
    static final FunctionDescriptor glVertexAttribI2ivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glVertexAttribI2ivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI2ivEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$48.glVertexAttribI2ivEXT$FUNC, false
    );
    static final FunctionDescriptor glVertexAttribI3ivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glVertexAttribI3ivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI3ivEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$48.glVertexAttribI3ivEXT$FUNC, false
    );
    static final FunctionDescriptor glVertexAttribI4ivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glVertexAttribI4ivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glVertexAttribI4ivEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$48.glVertexAttribI4ivEXT$FUNC, false
    );
}


