// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface glutTimerFunc$func {

    void apply(int x0);
    static MemoryAddress allocate(glutTimerFunc$func fi) {
        return RuntimeHelper.upcallStub(glutTimerFunc$func.class, fi, constants$189.glutTimerFunc$func$FUNC, "(I)V");
    }
    static MemoryAddress allocate(glutTimerFunc$func fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(glutTimerFunc$func.class, fi, constants$189.glutTimerFunc$func$FUNC, "(I)V", scope);
    }
    static glutTimerFunc$func ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$189.glutTimerFunc$func$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


