// Generated by jextract

package opengl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class glut_h extends glut_h_3 {

    static {
        System.loadLibrary("GL");
        System.load("/System/Library/Frameworks/GLUT.framework/Versions/Current/GLUT");
    }

    static final SymbolLookup LIBRARIES = RuntimeHelper.lookup();    /* package-private */ glut_h() {}
    public static int __MAC_10_0() {
        return (int)1000L;
    }
    public static int __MAC_10_1() {
        return (int)1010L;
    }
    public static int __MAC_10_2() {
        return (int)1020L;
    }
    public static int __MAC_10_3() {
        return (int)1030L;
    }
    public static int __MAC_10_4() {
        return (int)1040L;
    }
    public static int __MAC_10_5() {
        return (int)1050L;
    }
    public static int __MAC_10_6() {
        return (int)1060L;
    }
    public static int __MAC_10_7() {
        return (int)1070L;
    }
    public static int __MAC_10_8() {
        return (int)1080L;
    }
    public static int __MAC_10_9() {
        return (int)1090L;
    }
    public static int __MAC_10_10() {
        return (int)101000L;
    }
    public static int __MAC_10_10_2() {
        return (int)101002L;
    }
    public static int __MAC_10_10_3() {
        return (int)101003L;
    }
    public static int __MAC_10_11() {
        return (int)101100L;
    }
    public static int __MAC_10_11_2() {
        return (int)101102L;
    }
    public static int __MAC_10_11_3() {
        return (int)101103L;
    }
    public static int __MAC_10_11_4() {
        return (int)101104L;
    }
    public static int __MAC_10_12() {
        return (int)101200L;
    }
    public static int __MAC_10_12_1() {
        return (int)101201L;
    }
    public static int __MAC_10_12_2() {
        return (int)101202L;
    }
    public static int __MAC_10_12_4() {
        return (int)101204L;
    }
    public static int __IPHONE_2_0() {
        return (int)20000L;
    }
    public static int __IPHONE_2_1() {
        return (int)20100L;
    }
    public static int __IPHONE_2_2() {
        return (int)20200L;
    }
    public static int __IPHONE_3_0() {
        return (int)30000L;
    }
    public static int __IPHONE_3_1() {
        return (int)30100L;
    }
    public static int __IPHONE_3_2() {
        return (int)30200L;
    }
    public static int __IPHONE_4_0() {
        return (int)40000L;
    }
    public static int __IPHONE_4_1() {
        return (int)40100L;
    }
    public static int __IPHONE_4_2() {
        return (int)40200L;
    }
    public static int __IPHONE_4_3() {
        return (int)40300L;
    }
    public static int __IPHONE_5_0() {
        return (int)50000L;
    }
    public static int __IPHONE_5_1() {
        return (int)50100L;
    }
    public static int __IPHONE_6_0() {
        return (int)60000L;
    }
    public static int __IPHONE_6_1() {
        return (int)60100L;
    }
    public static int __IPHONE_7_0() {
        return (int)70000L;
    }
    public static int __IPHONE_7_1() {
        return (int)70100L;
    }
    public static int __IPHONE_8_0() {
        return (int)80000L;
    }
    public static int __IPHONE_8_1() {
        return (int)80100L;
    }
    public static int __IPHONE_8_2() {
        return (int)80200L;
    }
    public static int __IPHONE_8_3() {
        return (int)80300L;
    }
    public static int __IPHONE_8_4() {
        return (int)80400L;
    }
    public static int __IPHONE_9_0() {
        return (int)90000L;
    }
    public static int __IPHONE_9_1() {
        return (int)90100L;
    }
    public static int __IPHONE_9_2() {
        return (int)90200L;
    }
    public static int __IPHONE_9_3() {
        return (int)90300L;
    }
    public static int __IPHONE_10_0() {
        return (int)100000L;
    }
    public static int __IPHONE_10_1() {
        return (int)100100L;
    }
    public static int __IPHONE_10_2() {
        return (int)100200L;
    }
    public static int __IPHONE_10_3() {
        return (int)100300L;
    }
    public static int __TVOS_9_0() {
        return (int)90000L;
    }
    public static int __TVOS_9_1() {
        return (int)90100L;
    }
    public static int __TVOS_9_2() {
        return (int)90200L;
    }
    public static int __TVOS_10_0() {
        return (int)100000L;
    }
    public static int __TVOS_10_0_1() {
        return (int)100001L;
    }
    public static int __TVOS_10_1() {
        return (int)100100L;
    }
    public static int __TVOS_10_2() {
        return (int)100200L;
    }
    public static int __WATCHOS_1_0() {
        return (int)10000L;
    }
    public static int __WATCHOS_2_0() {
        return (int)20000L;
    }
    public static int __WATCHOS_2_1() {
        return (int)20100L;
    }
    public static int __WATCHOS_2_2() {
        return (int)20200L;
    }
    public static int __WATCHOS_3_0() {
        return (int)30000L;
    }
    public static int __WATCHOS_3_1() {
        return (int)30100L;
    }
    public static int __WATCHOS_3_1_1() {
        return (int)30101L;
    }
    public static int __WATCHOS_3_2() {
        return (int)30200L;
    }
    public static int __WORDSIZE() {
        return (int)64L;
    }
    public static int __DARWIN_ONLY_64_BIT_INO_T() {
        return (int)0L;
    }
    public static int __DARWIN_ONLY_VERS_1050() {
        return (int)0L;
    }
    public static int __DARWIN_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int __DARWIN_UNIX03() {
        return (int)1L;
    }
    public static int __DARWIN_64_BIT_INO_T() {
        return (int)1L;
    }
    public static int __DARWIN_VERS_1050() {
        return (int)1L;
    }
    public static int __DARWIN_NON_CANCELABLE() {
        return (int)0L;
    }
    public static int __STDC_WANT_LIB_EXT1__() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_64_BIT_INODE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_UNIX_CONFORMANCE() {
        return (int)3L;
    }
    public static int __PTHREAD_SIZE__() {
        return (int)8176L;
    }
    public static int __PTHREAD_ATTR_SIZE__() {
        return (int)56L;
    }
    public static int __PTHREAD_MUTEXATTR_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_MUTEX_SIZE__() {
        return (int)56L;
    }
    public static int __PTHREAD_CONDATTR_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_COND_SIZE__() {
        return (int)40L;
    }
    public static int __PTHREAD_ONCE_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_RWLOCK_SIZE__() {
        return (int)192L;
    }
    public static int __PTHREAD_RWLOCKATTR_SIZE__() {
        return (int)16L;
    }
    public static int INT8_MAX() {
        return (int)127L;
    }
    public static int INT16_MAX() {
        return (int)32767L;
    }
    public static int INT32_MAX() {
        return (int)2147483647L;
    }
    public static int UINT8_MAX() {
        return (int)255L;
    }
    public static int UINT16_MAX() {
        return (int)65535L;
    }
    public static int GL_ARB_color_buffer_float() {
        return (int)1L;
    }
    public static int GL_ARB_depth_buffer_float() {
        return (int)1L;
    }
    public static int GL_ARB_depth_clamp() {
        return (int)1L;
    }
    public static int GL_ARB_depth_texture() {
        return (int)1L;
    }
    public static int GL_ARB_draw_buffers() {
        return (int)1L;
    }
    public static int GL_ARB_draw_elements_base_vertex() {
        return (int)1L;
    }
    public static int GL_ARB_draw_instanced() {
        return (int)1L;
    }
    public static int GL_ARB_fragment_program() {
        return (int)1L;
    }
    public static int GL_ARB_fragment_program_shadow() {
        return (int)1L;
    }
    public static int GL_ARB_fragment_shader() {
        return (int)1L;
    }
    public static int GL_ARB_framebuffer_object() {
        return (int)1L;
    }
    public static int GL_ARB_framebuffer_sRGB() {
        return (int)1L;
    }
    public static int GL_ARB_half_float_pixel() {
        return (int)1L;
    }
    public static int GL_ARB_half_float_vertex() {
        return (int)1L;
    }
    public static int GL_ARB_imaging() {
        return (int)1L;
    }
    public static int GL_ARB_instanced_arrays() {
        return (int)1L;
    }
    public static int GL_ARB_multisample() {
        return (int)1L;
    }
    public static int GL_ARB_multitexture() {
        return (int)1L;
    }
    public static int GL_ARB_occlusion_query() {
        return (int)1L;
    }
    public static int GL_ARB_pixel_buffer_object() {
        return (int)1L;
    }
    public static int GL_ARB_point_parameters() {
        return (int)1L;
    }
    public static int GL_ARB_point_sprite() {
        return (int)1L;
    }
    public static int GL_ARB_provoking_vertex() {
        return (int)1L;
    }
    public static int GL_ARB_seamless_cube_map() {
        return (int)1L;
    }
    public static int GL_ARB_shader_objects() {
        return (int)1L;
    }
    public static int GL_ARB_shader_texture_lod() {
        return (int)1L;
    }
    public static int GL_ARB_shading_language_100() {
        return (int)1L;
    }
    public static int GL_ARB_shadow() {
        return (int)1L;
    }
    public static int GL_ARB_shadow_ambient() {
        return (int)1L;
    }
    public static int GL_ARB_sync() {
        return (int)1L;
    }
    public static int GL_ARB_texture_border_clamp() {
        return (int)1L;
    }
    public static int GL_ARB_texture_compression() {
        return (int)1L;
    }
    public static int GL_ARB_texture_compression_rgtc() {
        return (int)1L;
    }
    public static int GL_ARB_texture_cube_map() {
        return (int)1L;
    }
    public static int GL_ARB_texture_env_add() {
        return (int)1L;
    }
    public static int GL_ARB_texture_env_combine() {
        return (int)1L;
    }
    public static int GL_ARB_texture_env_crossbar() {
        return (int)1L;
    }
    public static int GL_ARB_texture_env_dot3() {
        return (int)1L;
    }
    public static int GL_ARB_texture_float() {
        return (int)1L;
    }
    public static int GL_ARB_texture_mirrored_repeat() {
        return (int)1L;
    }
    public static int GL_ARB_texture_non_power_of_two() {
        return (int)1L;
    }
    public static int GL_ARB_texture_rectangle() {
        return (int)1L;
    }
    public static int GL_ARB_texture_rg() {
        return (int)1L;
    }
    public static int GL_ARB_transpose_matrix() {
        return (int)1L;
    }
    public static int GL_ARB_vertex_array_bgra() {
        return (int)1L;
    }
    public static int GL_ARB_vertex_blend() {
        return (int)1L;
    }
    public static int GL_ARB_vertex_buffer_object() {
        return (int)1L;
    }
    public static int GL_ARB_vertex_program() {
        return (int)1L;
    }
    public static int GL_ARB_vertex_shader() {
        return (int)1L;
    }
    public static int GL_ARB_window_pos() {
        return (int)1L;
    }
    public static int GL_EXT_abgr() {
        return (int)1L;
    }
    public static int GL_EXT_bgra() {
        return (int)1L;
    }
    public static int GL_EXT_bindable_uniform() {
        return (int)1L;
    }
    public static int GL_EXT_blend_color() {
        return (int)1L;
    }
    public static int GL_EXT_blend_equation_separate() {
        return (int)1L;
    }
    public static int GL_EXT_blend_func_separate() {
        return (int)1L;
    }
    public static int GL_EXT_blend_minmax() {
        return (int)1L;
    }
    public static int GL_EXT_blend_subtract() {
        return (int)1L;
    }
    public static int GL_EXT_clip_volume_hint() {
        return (int)1L;
    }
    public static int GL_EXT_debug_label() {
        return (int)1L;
    }
    public static int GL_EXT_debug_marker() {
        return (int)1L;
    }
    public static int GL_EXT_depth_bounds_test() {
        return (int)1L;
    }
    public static int GL_EXT_draw_buffers2() {
        return (int)1L;
    }
    public static int GL_EXT_draw_range_elements() {
        return (int)1L;
    }
    public static int GL_EXT_fog_coord() {
        return (int)1L;
    }
    public static int GL_EXT_framebuffer_blit() {
        return (int)1L;
    }
    public static int GL_EXT_framebuffer_multisample() {
        return (int)1L;
    }
    public static int GL_EXT_framebuffer_multisample_blit_scaled() {
        return (int)1L;
    }
    public static int GL_EXT_framebuffer_object() {
        return (int)1L;
    }
    public static int GL_EXT_framebuffer_sRGB() {
        return (int)1L;
    }
    public static int GL_EXT_geometry_shader4() {
        return (int)1L;
    }
    public static int GL_EXT_gpu_program_parameters() {
        return (int)1L;
    }
    public static int GL_EXT_gpu_shader4() {
        return (int)1L;
    }
    public static int GL_EXT_multi_draw_arrays() {
        return (int)1L;
    }
    public static int GL_EXT_packed_depth_stencil() {
        return (int)1L;
    }
    public static int GL_EXT_packed_float() {
        return (int)1L;
    }
    public static int GL_EXT_provoking_vertex() {
        return (int)1L;
    }
    public static int GL_EXT_rescale_normal() {
        return (int)1L;
    }
    public static int GL_EXT_secondary_color() {
        return (int)1L;
    }
    public static int GL_EXT_separate_specular_color() {
        return (int)1L;
    }
    public static int GL_EXT_shadow_funcs() {
        return (int)1L;
    }
    public static int GL_EXT_stencil_two_side() {
        return (int)1L;
    }
    public static int GL_EXT_stencil_wrap() {
        return (int)1L;
    }
    public static int GL_EXT_texture_array() {
        return (int)1L;
    }
    public static int GL_EXT_texture_compression_dxt1() {
        return (int)1L;
    }
    public static int GL_EXT_texture_compression_s3tc() {
        return (int)1L;
    }
    public static int GL_EXT_texture_env_add() {
        return (int)1L;
    }
    public static int GL_EXT_texture_filter_anisotropic() {
        return (int)1L;
    }
    public static int GL_EXT_texture_integer() {
        return (int)1L;
    }
    public static int GL_EXT_texture_lod_bias() {
        return (int)1L;
    }
    public static int GL_EXT_texture_mirror_clamp() {
        return (int)1L;
    }
    public static int GL_EXT_texture_rectangle() {
        return (int)1L;
    }
    public static int GL_EXT_texture_shared_exponent() {
        return (int)1L;
    }
    public static int GL_EXT_texture_sRGB() {
        return (int)1L;
    }
    public static int GL_EXT_texture_sRGB_decode() {
        return (int)1L;
    }
    public static int GL_EXT_timer_query() {
        return (int)1L;
    }
    public static int GL_EXT_transform_feedback() {
        return (int)1L;
    }
    public static int GL_EXT_vertex_array_bgra() {
        return (int)1L;
    }
    public static int GL_APPLE_aux_depth_stencil() {
        return (int)1L;
    }
    public static int GL_APPLE_client_storage() {
        return (int)1L;
    }
    public static int GL_APPLE_element_array() {
        return (int)1L;
    }
    public static int GL_APPLE_fence() {
        return (int)1L;
    }
    public static int GL_APPLE_float_pixels() {
        return (int)1L;
    }
    public static int GL_APPLE_flush_buffer_range() {
        return (int)1L;
    }
    public static int GL_APPLE_flush_render() {
        return (int)1L;
    }
    public static int GL_APPLE_object_purgeable() {
        return (int)1L;
    }
    public static int GL_APPLE_packed_pixels() {
        return (int)1L;
    }
    public static int GL_APPLE_pixel_buffer() {
        return (int)1L;
    }
    public static int GL_APPLE_rgb_422() {
        return (int)1L;
    }
    public static int GL_APPLE_row_bytes() {
        return (int)1L;
    }
    public static int GL_APPLE_specular_vector() {
        return (int)1L;
    }
    public static int GL_APPLE_texture_range() {
        return (int)1L;
    }
    public static int GL_APPLE_transform_hint() {
        return (int)1L;
    }
    public static int GL_APPLE_vertex_array_object() {
        return (int)1L;
    }
    public static int GL_APPLE_vertex_array_range() {
        return (int)1L;
    }
    public static int GL_APPLE_vertex_point_size() {
        return (int)1L;
    }
    public static int GL_APPLE_vertex_program_evaluators() {
        return (int)1L;
    }
    public static int GL_APPLE_ycbcr_422() {
        return (int)1L;
    }
    public static int GL_ATI_blend_equation_separate() {
        return (int)1L;
    }
    public static int GL_ATI_blend_weighted_minmax() {
        return (int)1L;
    }
    public static int GL_ATI_separate_stencil() {
        return (int)1L;
    }
    public static int GL_ATI_texture_compression_3dc() {
        return (int)1L;
    }
    public static int GL_ATI_texture_env_combine3() {
        return (int)1L;
    }
    public static int GL_ATI_texture_float() {
        return (int)1L;
    }
    public static int GL_ATI_texture_mirror_once() {
        return (int)1L;
    }
    public static int GL_IBM_rasterpos_clip() {
        return (int)1L;
    }
    public static int GL_NV_blend_square() {
        return (int)1L;
    }
    public static int GL_NV_conditional_render() {
        return (int)1L;
    }
    public static int GL_NV_depth_clamp() {
        return (int)1L;
    }
    public static int GL_NV_fog_distance() {
        return (int)1L;
    }
    public static int GL_NV_fragment_program_option() {
        return (int)1L;
    }
    public static int GL_NV_fragment_program2() {
        return (int)1L;
    }
    public static int GL_NV_light_max_exponent() {
        return (int)1L;
    }
    public static int GL_NV_multisample_filter_hint() {
        return (int)1L;
    }
    public static int GL_NV_point_sprite() {
        return (int)1L;
    }
    public static int GL_NV_texgen_reflection() {
        return (int)1L;
    }
    public static int GL_NV_texture_barrier() {
        return (int)1L;
    }
    public static int GL_NV_vertex_program2_option() {
        return (int)1L;
    }
    public static int GL_NV_vertex_program3() {
        return (int)1L;
    }
    public static int GL_SGI_color_matrix() {
        return (int)1L;
    }
    public static int GL_SGIS_generate_mipmap() {
        return (int)1L;
    }
    public static int GL_SGIS_texture_edge_clamp() {
        return (int)1L;
    }
    public static int GL_SGIS_texture_lod() {
        return (int)1L;
    }
    public static int GL_GLEXT_VERSION() {
        return (int)8L;
    }
    public static int GL_RGBA_FLOAT_MODE_ARB() {
        return (int)34848L;
    }
    public static int GL_CLAMP_VERTEX_COLOR_ARB() {
        return (int)35098L;
    }
    public static int GL_CLAMP_FRAGMENT_COLOR_ARB() {
        return (int)35099L;
    }
    public static int GL_CLAMP_READ_COLOR_ARB() {
        return (int)35100L;
    }
    public static int GL_FIXED_ONLY_ARB() {
        return (int)35101L;
    }
    public static int GL_DEPTH_COMPONENT32F() {
        return (int)36012L;
    }
    public static int GL_DEPTH32F_STENCIL8() {
        return (int)36013L;
    }
    public static int GL_FLOAT_32_UNSIGNED_INT_24_8_REV() {
        return (int)36269L;
    }
    public static int GL_DEPTH_CLAMP() {
        return (int)34383L;
    }
    public static int GL_DEPTH_COMPONENT16_ARB() {
        return (int)33189L;
    }
    public static int GL_DEPTH_COMPONENT24_ARB() {
        return (int)33190L;
    }
    public static int GL_DEPTH_COMPONENT32_ARB() {
        return (int)33191L;
    }
    public static int GL_TEXTURE_DEPTH_SIZE_ARB() {
        return (int)34890L;
    }
    public static int GL_DEPTH_TEXTURE_MODE_ARB() {
        return (int)34891L;
    }
    public static int GL_MAX_DRAW_BUFFERS_ARB() {
        return (int)34852L;
    }
    public static int GL_DRAW_BUFFER0_ARB() {
        return (int)34853L;
    }
    public static int GL_DRAW_BUFFER1_ARB() {
        return (int)34854L;
    }
    public static int GL_DRAW_BUFFER2_ARB() {
        return (int)34855L;
    }
    public static int GL_DRAW_BUFFER3_ARB() {
        return (int)34856L;
    }
    public static int GL_DRAW_BUFFER4_ARB() {
        return (int)34857L;
    }
    public static int GL_DRAW_BUFFER5_ARB() {
        return (int)34858L;
    }
    public static int GL_DRAW_BUFFER6_ARB() {
        return (int)34859L;
    }
    public static int GL_DRAW_BUFFER7_ARB() {
        return (int)34860L;
    }
    public static int GL_DRAW_BUFFER8_ARB() {
        return (int)34861L;
    }
    public static int GL_DRAW_BUFFER9_ARB() {
        return (int)34862L;
    }
    public static int GL_DRAW_BUFFER10_ARB() {
        return (int)34863L;
    }
    public static int GL_DRAW_BUFFER11_ARB() {
        return (int)34864L;
    }
    public static int GL_DRAW_BUFFER12_ARB() {
        return (int)34865L;
    }
    public static int GL_DRAW_BUFFER13_ARB() {
        return (int)34866L;
    }
    public static int GL_DRAW_BUFFER14_ARB() {
        return (int)34867L;
    }
    public static int GL_DRAW_BUFFER15_ARB() {
        return (int)34868L;
    }
    public static int GL_FRAGMENT_PROGRAM_ARB() {
        return (int)34820L;
    }
    public static int GL_PROGRAM_ALU_INSTRUCTIONS_ARB() {
        return (int)34821L;
    }
    public static int GL_PROGRAM_TEX_INSTRUCTIONS_ARB() {
        return (int)34822L;
    }
    public static int GL_PROGRAM_TEX_INDIRECTIONS_ARB() {
        return (int)34823L;
    }
    public static int GL_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB() {
        return (int)34824L;
    }
    public static int GL_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB() {
        return (int)34825L;
    }
    public static int GL_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB() {
        return (int)34826L;
    }
    public static int GL_MAX_PROGRAM_ALU_INSTRUCTIONS_ARB() {
        return (int)34827L;
    }
    public static int GL_MAX_PROGRAM_TEX_INSTRUCTIONS_ARB() {
        return (int)34828L;
    }
    public static int GL_MAX_PROGRAM_TEX_INDIRECTIONS_ARB() {
        return (int)34829L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS_ARB() {
        return (int)34830L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_TEX_INSTRUCTIONS_ARB() {
        return (int)34831L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS_ARB() {
        return (int)34832L;
    }
    public static int GL_MAX_TEXTURE_COORDS_ARB() {
        return (int)34929L;
    }
    public static int GL_MAX_TEXTURE_IMAGE_UNITS_ARB() {
        return (int)34930L;
    }
    public static int GL_FRAGMENT_SHADER_ARB() {
        return (int)35632L;
    }
    public static int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS_ARB() {
        return (int)35657L;
    }
    public static int GL_FRAGMENT_SHADER_DERIVATIVE_HINT_ARB() {
        return (int)35723L;
    }
    public static int GL_INVALID_FRAMEBUFFER_OPERATION() {
        return (int)1286L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING() {
        return (int)33296L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE() {
        return (int)33297L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE() {
        return (int)33298L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE() {
        return (int)33299L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE() {
        return (int)33300L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE() {
        return (int)33301L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE() {
        return (int)33302L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE() {
        return (int)33303L;
    }
    public static int GL_FRAMEBUFFER_DEFAULT() {
        return (int)33304L;
    }
    public static int GL_FRAMEBUFFER_UNDEFINED() {
        return (int)33305L;
    }
    public static int GL_DEPTH_STENCIL_ATTACHMENT() {
        return (int)33306L;
    }
    public static int GL_MAX_RENDERBUFFER_SIZE() {
        return (int)34024L;
    }
    public static int GL_DEPTH_STENCIL() {
        return (int)34041L;
    }
    public static int GL_UNSIGNED_INT_24_8() {
        return (int)34042L;
    }
    public static int GL_DEPTH24_STENCIL8() {
        return (int)35056L;
    }
    public static int GL_TEXTURE_STENCIL_SIZE() {
        return (int)35057L;
    }
    public static int GL_TEXTURE_RED_TYPE() {
        return (int)35856L;
    }
    public static int GL_TEXTURE_GREEN_TYPE() {
        return (int)35857L;
    }
    public static int GL_TEXTURE_BLUE_TYPE() {
        return (int)35858L;
    }
    public static int GL_TEXTURE_ALPHA_TYPE() {
        return (int)35859L;
    }
    public static int GL_TEXTURE_DEPTH_TYPE() {
        return (int)35862L;
    }
    public static int GL_UNSIGNED_NORMALIZED() {
        return (int)35863L;
    }
    public static int GL_FRAMEBUFFER_BINDING() {
        return (int)36006L;
    }
    public static int GL_RENDERBUFFER_BINDING() {
        return (int)36007L;
    }
    public static int GL_READ_FRAMEBUFFER() {
        return (int)36008L;
    }
    public static int GL_DRAW_FRAMEBUFFER() {
        return (int)36009L;
    }
    public static int GL_READ_FRAMEBUFFER_BINDING() {
        return (int)36010L;
    }
    public static int GL_RENDERBUFFER_SAMPLES() {
        return (int)36011L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE() {
        return (int)36048L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME() {
        return (int)36049L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL() {
        return (int)36050L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE() {
        return (int)36051L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER() {
        return (int)36052L;
    }
    public static int GL_FRAMEBUFFER_COMPLETE() {
        return (int)36053L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT() {
        return (int)36054L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT() {
        return (int)36055L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER() {
        return (int)36059L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER() {
        return (int)36060L;
    }
    public static int GL_FRAMEBUFFER_UNSUPPORTED() {
        return (int)36061L;
    }
    public static int GL_MAX_COLOR_ATTACHMENTS() {
        return (int)36063L;
    }
    public static int GL_COLOR_ATTACHMENT0() {
        return (int)36064L;
    }
    public static int GL_COLOR_ATTACHMENT1() {
        return (int)36065L;
    }
    public static int GL_COLOR_ATTACHMENT2() {
        return (int)36066L;
    }
    public static int GL_COLOR_ATTACHMENT3() {
        return (int)36067L;
    }
    public static int GL_COLOR_ATTACHMENT4() {
        return (int)36068L;
    }
    public static int GL_COLOR_ATTACHMENT5() {
        return (int)36069L;
    }
    public static int GL_COLOR_ATTACHMENT6() {
        return (int)36070L;
    }
    public static int GL_COLOR_ATTACHMENT7() {
        return (int)36071L;
    }
    public static int GL_COLOR_ATTACHMENT8() {
        return (int)36072L;
    }
    public static int GL_COLOR_ATTACHMENT9() {
        return (int)36073L;
    }
    public static int GL_COLOR_ATTACHMENT10() {
        return (int)36074L;
    }
    public static int GL_COLOR_ATTACHMENT11() {
        return (int)36075L;
    }
    public static int GL_COLOR_ATTACHMENT12() {
        return (int)36076L;
    }
    public static int GL_COLOR_ATTACHMENT13() {
        return (int)36077L;
    }
    public static int GL_COLOR_ATTACHMENT14() {
        return (int)36078L;
    }
    public static int GL_COLOR_ATTACHMENT15() {
        return (int)36079L;
    }
    public static int GL_DEPTH_ATTACHMENT() {
        return (int)36096L;
    }
    public static int GL_STENCIL_ATTACHMENT() {
        return (int)36128L;
    }
    public static int GL_FRAMEBUFFER() {
        return (int)36160L;
    }
    public static int GL_RENDERBUFFER() {
        return (int)36161L;
    }
    public static int GL_RENDERBUFFER_WIDTH() {
        return (int)36162L;
    }
    public static int GL_RENDERBUFFER_HEIGHT() {
        return (int)36163L;
    }
    public static int GL_RENDERBUFFER_INTERNAL_FORMAT() {
        return (int)36164L;
    }
    public static int GL_STENCIL_INDEX1() {
        return (int)36166L;
    }
    public static int GL_STENCIL_INDEX4() {
        return (int)36167L;
    }
    public static int GL_STENCIL_INDEX8() {
        return (int)36168L;
    }
    public static int GL_STENCIL_INDEX16() {
        return (int)36169L;
    }
    public static int GL_RENDERBUFFER_RED_SIZE() {
        return (int)36176L;
    }
    public static int GL_RENDERBUFFER_GREEN_SIZE() {
        return (int)36177L;
    }
    public static int GL_RENDERBUFFER_BLUE_SIZE() {
        return (int)36178L;
    }
    public static int GL_RENDERBUFFER_ALPHA_SIZE() {
        return (int)36179L;
    }
    public static int GL_RENDERBUFFER_DEPTH_SIZE() {
        return (int)36180L;
    }
    public static int GL_RENDERBUFFER_STENCIL_SIZE() {
        return (int)36181L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE() {
        return (int)36182L;
    }
    public static int GL_MAX_SAMPLES() {
        return (int)36183L;
    }
    public static int GL_FRAMEBUFFER_SRGB() {
        return (int)36281L;
    }
    public static int GL_HALF_FLOAT_ARB() {
        return (int)5131L;
    }
    public static int GL_HALF_FLOAT() {
        return (int)5131L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_DIVISOR_ARB() {
        return (int)35070L;
    }
    public static int GL_MULTISAMPLE_ARB() {
        return (int)32925L;
    }
    public static int GL_SAMPLE_ALPHA_TO_COVERAGE_ARB() {
        return (int)32926L;
    }
    public static int GL_SAMPLE_ALPHA_TO_ONE_ARB() {
        return (int)32927L;
    }
    public static int GL_SAMPLE_COVERAGE_ARB() {
        return (int)32928L;
    }
    public static int GL_SAMPLE_BUFFERS_ARB() {
        return (int)32936L;
    }
    public static int GL_SAMPLES_ARB() {
        return (int)32937L;
    }
    public static int GL_SAMPLE_COVERAGE_VALUE_ARB() {
        return (int)32938L;
    }
    public static int GL_SAMPLE_COVERAGE_INVERT_ARB() {
        return (int)32939L;
    }
    public static int GL_MULTISAMPLE_BIT_ARB() {
        return (int)536870912L;
    }
    public static int GL_TEXTURE0_ARB() {
        return (int)33984L;
    }
    public static int GL_TEXTURE1_ARB() {
        return (int)33985L;
    }
    public static int GL_TEXTURE2_ARB() {
        return (int)33986L;
    }
    public static int GL_TEXTURE3_ARB() {
        return (int)33987L;
    }
    public static int GL_TEXTURE4_ARB() {
        return (int)33988L;
    }
    public static int GL_TEXTURE5_ARB() {
        return (int)33989L;
    }
    public static int GL_TEXTURE6_ARB() {
        return (int)33990L;
    }
    public static int GL_TEXTURE7_ARB() {
        return (int)33991L;
    }
    public static int GL_TEXTURE8_ARB() {
        return (int)33992L;
    }
    public static int GL_TEXTURE9_ARB() {
        return (int)33993L;
    }
    public static int GL_TEXTURE10_ARB() {
        return (int)33994L;
    }
    public static int GL_TEXTURE11_ARB() {
        return (int)33995L;
    }
    public static int GL_TEXTURE12_ARB() {
        return (int)33996L;
    }
    public static int GL_TEXTURE13_ARB() {
        return (int)33997L;
    }
    public static int GL_TEXTURE14_ARB() {
        return (int)33998L;
    }
    public static int GL_TEXTURE15_ARB() {
        return (int)33999L;
    }
    public static int GL_TEXTURE16_ARB() {
        return (int)34000L;
    }
    public static int GL_TEXTURE17_ARB() {
        return (int)34001L;
    }
    public static int GL_TEXTURE18_ARB() {
        return (int)34002L;
    }
    public static int GL_TEXTURE19_ARB() {
        return (int)34003L;
    }
    public static int GL_TEXTURE20_ARB() {
        return (int)34004L;
    }
    public static int GL_TEXTURE21_ARB() {
        return (int)34005L;
    }
    public static int GL_TEXTURE22_ARB() {
        return (int)34006L;
    }
    public static int GL_TEXTURE23_ARB() {
        return (int)34007L;
    }
    public static int GL_TEXTURE24_ARB() {
        return (int)34008L;
    }
    public static int GL_TEXTURE25_ARB() {
        return (int)34009L;
    }
    public static int GL_TEXTURE26_ARB() {
        return (int)34010L;
    }
    public static int GL_TEXTURE27_ARB() {
        return (int)34011L;
    }
    public static int GL_TEXTURE28_ARB() {
        return (int)34012L;
    }
    public static int GL_TEXTURE29_ARB() {
        return (int)34013L;
    }
    public static int GL_TEXTURE30_ARB() {
        return (int)34014L;
    }
    public static int GL_TEXTURE31_ARB() {
        return (int)34015L;
    }
    public static int GL_ACTIVE_TEXTURE_ARB() {
        return (int)34016L;
    }
    public static int GL_CLIENT_ACTIVE_TEXTURE_ARB() {
        return (int)34017L;
    }
    public static int GL_MAX_TEXTURE_UNITS_ARB() {
        return (int)34018L;
    }
    public static int GL_SAMPLES_PASSED_ARB() {
        return (int)35092L;
    }
    public static int GL_QUERY_COUNTER_BITS_ARB() {
        return (int)34916L;
    }
    public static int GL_CURRENT_QUERY_ARB() {
        return (int)34917L;
    }
    public static int GL_QUERY_RESULT_ARB() {
        return (int)34918L;
    }
    public static int GL_QUERY_RESULT_AVAILABLE_ARB() {
        return (int)34919L;
    }
    public static int GL_PIXEL_PACK_BUFFER_ARB() {
        return (int)35051L;
    }
    public static int GL_PIXEL_UNPACK_BUFFER_ARB() {
        return (int)35052L;
    }
    public static int GL_PIXEL_PACK_BUFFER_BINDING_ARB() {
        return (int)35053L;
    }
    public static int GL_PIXEL_UNPACK_BUFFER_BINDING_ARB() {
        return (int)35055L;
    }
    public static int GL_POINT_SIZE_MIN_ARB() {
        return (int)33062L;
    }
    public static int GL_POINT_SIZE_MAX_ARB() {
        return (int)33063L;
    }
    public static int GL_POINT_FADE_THRESHOLD_SIZE_ARB() {
        return (int)33064L;
    }
    public static int GL_POINT_DISTANCE_ATTENUATION_ARB() {
        return (int)33065L;
    }
    public static int GL_POINT_SPRITE_ARB() {
        return (int)34913L;
    }
    public static int GL_COORD_REPLACE_ARB() {
        return (int)34914L;
    }
    public static int GL_FIRST_VERTEX_CONVENTION() {
        return (int)36429L;
    }
    public static int GL_LAST_VERTEX_CONVENTION() {
        return (int)36430L;
    }
    public static int GL_PROVOKING_VERTEX() {
        return (int)36431L;
    }
    public static int GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION() {
        return (int)36428L;
    }
    public static int GL_TEXTURE_CUBE_MAP_SEAMLESS() {
        return (int)34895L;
    }
    public static int GL_PROGRAM_OBJECT_ARB() {
        return (int)35648L;
    }
    public static int GL_OBJECT_TYPE_ARB() {
        return (int)35662L;
    }
    public static int GL_OBJECT_SUBTYPE_ARB() {
        return (int)35663L;
    }
    public static int GL_OBJECT_DELETE_STATUS_ARB() {
        return (int)35712L;
    }
    public static int GL_OBJECT_COMPILE_STATUS_ARB() {
        return (int)35713L;
    }
    public static int GL_OBJECT_LINK_STATUS_ARB() {
        return (int)35714L;
    }
    public static int GL_OBJECT_VALIDATE_STATUS_ARB() {
        return (int)35715L;
    }
    public static int GL_OBJECT_INFO_LOG_LENGTH_ARB() {
        return (int)35716L;
    }
    public static int GL_OBJECT_ATTACHED_OBJECTS_ARB() {
        return (int)35717L;
    }
    public static int GL_OBJECT_ACTIVE_UNIFORMS_ARB() {
        return (int)35718L;
    }
    public static int GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH_ARB() {
        return (int)35719L;
    }
    public static int GL_OBJECT_SHADER_SOURCE_LENGTH_ARB() {
        return (int)35720L;
    }
    public static int GL_SHADER_OBJECT_ARB() {
        return (int)35656L;
    }
    public static int GL_FLOAT_VEC2_ARB() {
        return (int)35664L;
    }
    public static int GL_FLOAT_VEC3_ARB() {
        return (int)35665L;
    }
    public static int GL_FLOAT_VEC4_ARB() {
        return (int)35666L;
    }
    public static int GL_INT_VEC2_ARB() {
        return (int)35667L;
    }
    public static int GL_INT_VEC3_ARB() {
        return (int)35668L;
    }
    public static int GL_INT_VEC4_ARB() {
        return (int)35669L;
    }
    public static int GL_BOOL_ARB() {
        return (int)35670L;
    }
    public static int GL_BOOL_VEC2_ARB() {
        return (int)35671L;
    }
    public static int GL_BOOL_VEC3_ARB() {
        return (int)35672L;
    }
    public static int GL_BOOL_VEC4_ARB() {
        return (int)35673L;
    }
    public static int GL_FLOAT_MAT2_ARB() {
        return (int)35674L;
    }
    public static int GL_FLOAT_MAT3_ARB() {
        return (int)35675L;
    }
    public static int GL_FLOAT_MAT4_ARB() {
        return (int)35676L;
    }
    public static int GL_SAMPLER_1D_ARB() {
        return (int)35677L;
    }
    public static int GL_SAMPLER_2D_ARB() {
        return (int)35678L;
    }
    public static int GL_SAMPLER_3D_ARB() {
        return (int)35679L;
    }
    public static int GL_SAMPLER_CUBE_ARB() {
        return (int)35680L;
    }
    public static int GL_SAMPLER_1D_SHADOW_ARB() {
        return (int)35681L;
    }
    public static int GL_SAMPLER_2D_SHADOW_ARB() {
        return (int)35682L;
    }
    public static int GL_SAMPLER_2D_RECT_ARB() {
        return (int)35683L;
    }
    public static int GL_SAMPLER_2D_RECT_SHADOW_ARB() {
        return (int)35684L;
    }
    public static int GL_SHADING_LANGUAGE_VERSION_ARB() {
        return (int)35724L;
    }
    public static int GL_TEXTURE_COMPARE_MODE_ARB() {
        return (int)34892L;
    }
    public static int GL_TEXTURE_COMPARE_FUNC_ARB() {
        return (int)34893L;
    }
    public static int GL_COMPARE_R_TO_TEXTURE_ARB() {
        return (int)34894L;
    }
    public static int GL_TEXTURE_COMPARE_FAIL_VALUE_ARB() {
        return (int)32959L;
    }
    public static int GL_MAX_SERVER_WAIT_TIMEOUT() {
        return (int)37137L;
    }
    public static int GL_OBJECT_TYPE() {
        return (int)37138L;
    }
    public static int GL_SYNC_CONDITION() {
        return (int)37139L;
    }
    public static int GL_SYNC_STATUS() {
        return (int)37140L;
    }
    public static int GL_SYNC_FLAGS() {
        return (int)37141L;
    }
    public static int GL_SYNC_FENCE() {
        return (int)37142L;
    }
    public static int GL_SYNC_GPU_COMMANDS_COMPLETE() {
        return (int)37143L;
    }
    public static int GL_UNSIGNALED() {
        return (int)37144L;
    }
    public static int GL_SIGNALED() {
        return (int)37145L;
    }
    public static int GL_ALREADY_SIGNALED() {
        return (int)37146L;
    }
    public static int GL_TIMEOUT_EXPIRED() {
        return (int)37147L;
    }
    public static int GL_CONDITION_SATISFIED() {
        return (int)37148L;
    }
    public static int GL_WAIT_FAILED() {
        return (int)37149L;
    }
    public static int GL_SYNC_FLUSH_COMMANDS_BIT() {
        return (int)1L;
    }
    public static int GL_CLAMP_TO_BORDER_ARB() {
        return (int)33069L;
    }
    public static int GL_COMPRESSED_ALPHA_ARB() {
        return (int)34025L;
    }
    public static int GL_COMPRESSED_LUMINANCE_ARB() {
        return (int)34026L;
    }
    public static int GL_COMPRESSED_LUMINANCE_ALPHA_ARB() {
        return (int)34027L;
    }
    public static int GL_COMPRESSED_INTENSITY_ARB() {
        return (int)34028L;
    }
    public static int GL_COMPRESSED_RGB_ARB() {
        return (int)34029L;
    }
    public static int GL_COMPRESSED_RGBA_ARB() {
        return (int)34030L;
    }
    public static int GL_TEXTURE_COMPRESSION_HINT_ARB() {
        return (int)34031L;
    }
    public static int GL_TEXTURE_COMPRESSED_IMAGE_SIZE_ARB() {
        return (int)34464L;
    }
    public static int GL_TEXTURE_COMPRESSED_ARB() {
        return (int)34465L;
    }
    public static int GL_NUM_COMPRESSED_TEXTURE_FORMATS_ARB() {
        return (int)34466L;
    }
    public static int GL_COMPRESSED_TEXTURE_FORMATS_ARB() {
        return (int)34467L;
    }
    public static int GL_COMPRESSED_RED_RGTC1() {
        return (int)36283L;
    }
    public static int GL_COMPRESSED_SIGNED_RED_RGTC1() {
        return (int)36284L;
    }
    public static int GL_COMPRESSED_RG_RGTC2() {
        return (int)36285L;
    }
    public static int GL_COMPRESSED_SIGNED_RG_RGTC2() {
        return (int)36286L;
    }
    public static int GL_NORMAL_MAP_ARB() {
        return (int)34065L;
    }
    public static int GL_REFLECTION_MAP_ARB() {
        return (int)34066L;
    }
    public static int GL_TEXTURE_CUBE_MAP_ARB() {
        return (int)34067L;
    }
    public static int GL_TEXTURE_BINDING_CUBE_MAP_ARB() {
        return (int)34068L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB() {
        return (int)34069L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB() {
        return (int)34070L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB() {
        return (int)34071L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB() {
        return (int)34072L;
    }
    public static int GL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB() {
        return (int)34073L;
    }
    public static int GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB() {
        return (int)34074L;
    }
    public static int GL_PROXY_TEXTURE_CUBE_MAP_ARB() {
        return (int)34075L;
    }
    public static int GL_MAX_CUBE_MAP_TEXTURE_SIZE_ARB() {
        return (int)34076L;
    }
    public static int GL_COMBINE_ARB() {
        return (int)34160L;
    }
    public static int GL_COMBINE_RGB_ARB() {
        return (int)34161L;
    }
    public static int GL_COMBINE_ALPHA_ARB() {
        return (int)34162L;
    }
    public static int GL_RGB_SCALE_ARB() {
        return (int)34163L;
    }
    public static int GL_ADD_SIGNED_ARB() {
        return (int)34164L;
    }
    public static int GL_INTERPOLATE_ARB() {
        return (int)34165L;
    }
    public static int GL_CONSTANT_ARB() {
        return (int)34166L;
    }
    public static int GL_PRIMARY_COLOR_ARB() {
        return (int)34167L;
    }
    public static int GL_PREVIOUS_ARB() {
        return (int)34168L;
    }
    public static int GL_SUBTRACT_ARB() {
        return (int)34023L;
    }
    public static int GL_SOURCE0_RGB_ARB() {
        return (int)34176L;
    }
    public static int GL_SOURCE1_RGB_ARB() {
        return (int)34177L;
    }
    public static int GL_SOURCE2_RGB_ARB() {
        return (int)34178L;
    }
    public static int GL_SOURCE0_ALPHA_ARB() {
        return (int)34184L;
    }
    public static int GL_SOURCE1_ALPHA_ARB() {
        return (int)34185L;
    }
    public static int GL_SOURCE2_ALPHA_ARB() {
        return (int)34186L;
    }
    public static int GL_OPERAND0_RGB_ARB() {
        return (int)34192L;
    }
    public static int GL_OPERAND1_RGB_ARB() {
        return (int)34193L;
    }
    public static int GL_OPERAND2_RGB_ARB() {
        return (int)34194L;
    }
    public static int GL_OPERAND0_ALPHA_ARB() {
        return (int)34200L;
    }
    public static int GL_OPERAND1_ALPHA_ARB() {
        return (int)34201L;
    }
    public static int GL_OPERAND2_ALPHA_ARB() {
        return (int)34202L;
    }
    public static int GL_DOT3_RGB_ARB() {
        return (int)34478L;
    }
    public static int GL_DOT3_RGBA_ARB() {
        return (int)34479L;
    }
    public static int GL_TEXTURE_RED_TYPE_ARB() {
        return (int)35856L;
    }
    public static int GL_TEXTURE_GREEN_TYPE_ARB() {
        return (int)35857L;
    }
    public static int GL_TEXTURE_BLUE_TYPE_ARB() {
        return (int)35858L;
    }
    public static int GL_TEXTURE_ALPHA_TYPE_ARB() {
        return (int)35859L;
    }
    public static int GL_TEXTURE_LUMINANCE_TYPE_ARB() {
        return (int)35860L;
    }
    public static int GL_TEXTURE_INTENSITY_TYPE_ARB() {
        return (int)35861L;
    }
    public static int GL_TEXTURE_DEPTH_TYPE_ARB() {
        return (int)35862L;
    }
    public static int GL_UNSIGNED_NORMALIZED_ARB() {
        return (int)35863L;
    }
    public static int GL_RGBA32F_ARB() {
        return (int)34836L;
    }
    public static int GL_RGB32F_ARB() {
        return (int)34837L;
    }
    public static int GL_ALPHA32F_ARB() {
        return (int)34838L;
    }
    public static int GL_INTENSITY32F_ARB() {
        return (int)34839L;
    }
    public static int GL_LUMINANCE32F_ARB() {
        return (int)34840L;
    }
    public static int GL_LUMINANCE_ALPHA32F_ARB() {
        return (int)34841L;
    }
    public static int GL_RGBA16F_ARB() {
        return (int)34842L;
    }
    public static int GL_RGB16F_ARB() {
        return (int)34843L;
    }
    public static int GL_ALPHA16F_ARB() {
        return (int)34844L;
    }
    public static int GL_INTENSITY16F_ARB() {
        return (int)34845L;
    }
    public static int GL_LUMINANCE16F_ARB() {
        return (int)34846L;
    }
    public static int GL_LUMINANCE_ALPHA16F_ARB() {
        return (int)34847L;
    }
    public static int GL_MIRRORED_REPEAT_ARB() {
        return (int)33648L;
    }
    public static int GL_TEXTURE_RECTANGLE_ARB() {
        return (int)34037L;
    }
    public static int GL_TEXTURE_BINDING_RECTANGLE_ARB() {
        return (int)34038L;
    }
    public static int GL_PROXY_TEXTURE_RECTANGLE_ARB() {
        return (int)34039L;
    }
    public static int GL_MAX_RECTANGLE_TEXTURE_SIZE_ARB() {
        return (int)34040L;
    }
    public static int GL_COMPRESSED_RED() {
        return (int)33317L;
    }
    public static int GL_COMPRESSED_RG() {
        return (int)33318L;
    }
    public static int GL_RG() {
        return (int)33319L;
    }
    public static int GL_RG_INTEGER() {
        return (int)33320L;
    }
    public static int GL_R8() {
        return (int)33321L;
    }
    public static int GL_R16() {
        return (int)33322L;
    }
    public static int GL_RG8() {
        return (int)33323L;
    }
    public static int GL_RG16() {
        return (int)33324L;
    }
    public static int GL_R16F() {
        return (int)33325L;
    }
    public static int GL_R32F() {
        return (int)33326L;
    }
    public static int GL_RG16F() {
        return (int)33327L;
    }
    public static int GL_RG32F() {
        return (int)33328L;
    }
    public static int GL_R8I() {
        return (int)33329L;
    }
    public static int GL_R8UI() {
        return (int)33330L;
    }
    public static int GL_R16I() {
        return (int)33331L;
    }
    public static int GL_R16UI() {
        return (int)33332L;
    }
    public static int GL_R32I() {
        return (int)33333L;
    }
    public static int GL_R32UI() {
        return (int)33334L;
    }
    public static int GL_RG8I() {
        return (int)33335L;
    }
    public static int GL_RG8UI() {
        return (int)33336L;
    }
    public static int GL_RG16I() {
        return (int)33337L;
    }
    public static int GL_RG16UI() {
        return (int)33338L;
    }
    public static int GL_RG32I() {
        return (int)33339L;
    }
    public static int GL_RG32UI() {
        return (int)33340L;
    }
    public static int GL_TRANSPOSE_MODELVIEW_MATRIX_ARB() {
        return (int)34019L;
    }
    public static int GL_TRANSPOSE_PROJECTION_MATRIX_ARB() {
        return (int)34020L;
    }
    public static int GL_TRANSPOSE_TEXTURE_MATRIX_ARB() {
        return (int)34021L;
    }
    public static int GL_TRANSPOSE_COLOR_MATRIX_ARB() {
        return (int)34022L;
    }
    public static int GL_MAX_VERTEX_UNITS_ARB() {
        return (int)34468L;
    }
    public static int GL_ACTIVE_VERTEX_UNITS_ARB() {
        return (int)34469L;
    }
    public static int GL_WEIGHT_SUM_UNITY_ARB() {
        return (int)34470L;
    }
    public static int GL_VERTEX_BLEND_ARB() {
        return (int)34471L;
    }
    public static int GL_CURRENT_WEIGHT_ARB() {
        return (int)34472L;
    }
    public static int GL_WEIGHT_ARRAY_TYPE_ARB() {
        return (int)34473L;
    }
    public static int GL_WEIGHT_ARRAY_STRIDE_ARB() {
        return (int)34474L;
    }
    public static int GL_WEIGHT_ARRAY_SIZE_ARB() {
        return (int)34475L;
    }
    public static int GL_WEIGHT_ARRAY_POINTER_ARB() {
        return (int)34476L;
    }
    public static int GL_WEIGHT_ARRAY_ARB() {
        return (int)34477L;
    }
    public static int GL_MODELVIEW0_ARB() {
        return (int)5888L;
    }
    public static int GL_MODELVIEW1_ARB() {
        return (int)34058L;
    }
    public static int GL_MODELVIEW2_ARB() {
        return (int)34594L;
    }
    public static int GL_MODELVIEW3_ARB() {
        return (int)34595L;
    }
    public static int GL_MODELVIEW4_ARB() {
        return (int)34596L;
    }
    public static int GL_MODELVIEW5_ARB() {
        return (int)34597L;
    }
    public static int GL_MODELVIEW6_ARB() {
        return (int)34598L;
    }
    public static int GL_MODELVIEW7_ARB() {
        return (int)34599L;
    }
    public static int GL_MODELVIEW8_ARB() {
        return (int)34600L;
    }
    public static int GL_MODELVIEW9_ARB() {
        return (int)34601L;
    }
    public static int GL_MODELVIEW10_ARB() {
        return (int)34602L;
    }
    public static int GL_MODELVIEW11_ARB() {
        return (int)34603L;
    }
    public static int GL_MODELVIEW12_ARB() {
        return (int)34604L;
    }
    public static int GL_MODELVIEW13_ARB() {
        return (int)34605L;
    }
    public static int GL_MODELVIEW14_ARB() {
        return (int)34606L;
    }
    public static int GL_MODELVIEW15_ARB() {
        return (int)34607L;
    }
    public static int GL_MODELVIEW16_ARB() {
        return (int)34608L;
    }
    public static int GL_MODELVIEW17_ARB() {
        return (int)34609L;
    }
    public static int GL_MODELVIEW18_ARB() {
        return (int)34610L;
    }
    public static int GL_MODELVIEW19_ARB() {
        return (int)34611L;
    }
    public static int GL_MODELVIEW20_ARB() {
        return (int)34612L;
    }
    public static int GL_MODELVIEW21_ARB() {
        return (int)34613L;
    }
    public static int GL_MODELVIEW22_ARB() {
        return (int)34614L;
    }
    public static int GL_MODELVIEW23_ARB() {
        return (int)34615L;
    }
    public static int GL_MODELVIEW24_ARB() {
        return (int)34616L;
    }
    public static int GL_MODELVIEW25_ARB() {
        return (int)34617L;
    }
    public static int GL_MODELVIEW26_ARB() {
        return (int)34618L;
    }
    public static int GL_MODELVIEW27_ARB() {
        return (int)34619L;
    }
    public static int GL_MODELVIEW28_ARB() {
        return (int)34620L;
    }
    public static int GL_MODELVIEW29_ARB() {
        return (int)34621L;
    }
    public static int GL_MODELVIEW30_ARB() {
        return (int)34622L;
    }
    public static int GL_MODELVIEW31_ARB() {
        return (int)34623L;
    }
    public static int GL_ARRAY_BUFFER_ARB() {
        return (int)34962L;
    }
    public static int GL_ELEMENT_ARRAY_BUFFER_ARB() {
        return (int)34963L;
    }
    public static int GL_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34964L;
    }
    public static int GL_ELEMENT_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34965L;
    }
    public static int GL_VERTEX_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34966L;
    }
    public static int GL_NORMAL_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34967L;
    }
    public static int GL_COLOR_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34968L;
    }
    public static int GL_INDEX_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34969L;
    }
    public static int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34970L;
    }
    public static int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34971L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34972L;
    }
    public static int GL_FOG_COORD_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34973L;
    }
    public static int GL_WEIGHT_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34974L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34975L;
    }
    public static int GL_STREAM_DRAW_ARB() {
        return (int)35040L;
    }
    public static int GL_STREAM_READ_ARB() {
        return (int)35041L;
    }
    public static int GL_STREAM_COPY_ARB() {
        return (int)35042L;
    }
    public static int GL_STATIC_DRAW_ARB() {
        return (int)35044L;
    }
    public static int GL_STATIC_READ_ARB() {
        return (int)35045L;
    }
    public static int GL_STATIC_COPY_ARB() {
        return (int)35046L;
    }
    public static int GL_DYNAMIC_DRAW_ARB() {
        return (int)35048L;
    }
    public static int GL_DYNAMIC_READ_ARB() {
        return (int)35049L;
    }
    public static int GL_DYNAMIC_COPY_ARB() {
        return (int)35050L;
    }
    public static int GL_READ_ONLY_ARB() {
        return (int)35000L;
    }
    public static int GL_WRITE_ONLY_ARB() {
        return (int)35001L;
    }
    public static int GL_READ_WRITE_ARB() {
        return (int)35002L;
    }
    public static int GL_BUFFER_SIZE_ARB() {
        return (int)34660L;
    }
    public static int GL_BUFFER_USAGE_ARB() {
        return (int)34661L;
    }
    public static int GL_BUFFER_ACCESS_ARB() {
        return (int)35003L;
    }
    public static int GL_BUFFER_MAPPED_ARB() {
        return (int)35004L;
    }
    public static int GL_BUFFER_MAP_POINTER_ARB() {
        return (int)35005L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING_ARB() {
        return (int)34973L;
    }
    public static int GL_VERTEX_PROGRAM_ARB() {
        return (int)34336L;
    }
    public static int GL_VERTEX_PROGRAM_POINT_SIZE_ARB() {
        return (int)34370L;
    }
    public static int GL_VERTEX_PROGRAM_TWO_SIDE_ARB() {
        return (int)34371L;
    }
    public static int GL_PROGRAM_FORMAT_ASCII_ARB() {
        return (int)34933L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB() {
        return (int)34338L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB() {
        return (int)34339L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB() {
        return (int)34340L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB() {
        return (int)34341L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB() {
        return (int)34922L;
    }
    public static int GL_CURRENT_VERTEX_ATTRIB_ARB() {
        return (int)34342L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB() {
        return (int)34373L;
    }
    public static int GL_PROGRAM_LENGTH_ARB() {
        return (int)34343L;
    }
    public static int GL_PROGRAM_FORMAT_ARB() {
        return (int)34934L;
    }
    public static int GL_PROGRAM_NAME_ARB() {
        return (int)34423L;
    }
    public static int GL_PROGRAM_BINDING_ARB() {
        return (int)34423L;
    }
    public static int GL_PROGRAM_INSTRUCTIONS_ARB() {
        return (int)34976L;
    }
    public static int GL_MAX_PROGRAM_INSTRUCTIONS_ARB() {
        return (int)34977L;
    }
    public static int GL_PROGRAM_NATIVE_INSTRUCTIONS_ARB() {
        return (int)34978L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB() {
        return (int)34979L;
    }
    public static int GL_PROGRAM_TEMPORARIES_ARB() {
        return (int)34980L;
    }
    public static int GL_MAX_PROGRAM_TEMPORARIES_ARB() {
        return (int)34981L;
    }
    public static int GL_PROGRAM_NATIVE_TEMPORARIES_ARB() {
        return (int)34982L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB() {
        return (int)34983L;
    }
    public static int GL_PROGRAM_PARAMETERS_ARB() {
        return (int)34984L;
    }
    public static int GL_MAX_PROGRAM_PARAMETERS_ARB() {
        return (int)34985L;
    }
    public static int GL_PROGRAM_NATIVE_PARAMETERS_ARB() {
        return (int)34986L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB() {
        return (int)34987L;
    }
    public static int GL_PROGRAM_ATTRIBS_ARB() {
        return (int)34988L;
    }
    public static int GL_MAX_PROGRAM_ATTRIBS_ARB() {
        return (int)34989L;
    }
    public static int GL_PROGRAM_NATIVE_ATTRIBS_ARB() {
        return (int)34990L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB() {
        return (int)34991L;
    }
    public static int GL_PROGRAM_ADDRESS_REGISTERS_ARB() {
        return (int)34992L;
    }
    public static int GL_MAX_PROGRAM_ADDRESS_REGISTERS_ARB() {
        return (int)34993L;
    }
    public static int GL_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB() {
        return (int)34994L;
    }
    public static int GL_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB() {
        return (int)34995L;
    }
    public static int GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB() {
        return (int)34996L;
    }
    public static int GL_MAX_PROGRAM_ENV_PARAMETERS_ARB() {
        return (int)34997L;
    }
    public static int GL_PROGRAM_UNDER_NATIVE_LIMITS_ARB() {
        return (int)34998L;
    }
    public static int GL_PROGRAM_STRING_ARB() {
        return (int)34344L;
    }
    public static int GL_PROGRAM_ERROR_POSITION_ARB() {
        return (int)34379L;
    }
    public static int GL_CURRENT_MATRIX_ARB() {
        return (int)34369L;
    }
    public static int GL_TRANSPOSE_CURRENT_MATRIX_ARB() {
        return (int)34999L;
    }
    public static int GL_CURRENT_MATRIX_STACK_DEPTH_ARB() {
        return (int)34368L;
    }
    public static int GL_MAX_VERTEX_ATTRIBS_ARB() {
        return (int)34921L;
    }
    public static int GL_MAX_PROGRAM_MATRICES_ARB() {
        return (int)34351L;
    }
    public static int GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB() {
        return (int)34350L;
    }
    public static int GL_PROGRAM_ERROR_STRING_ARB() {
        return (int)34932L;
    }
    public static int GL_MATRIX0_ARB() {
        return (int)35008L;
    }
    public static int GL_MATRIX1_ARB() {
        return (int)35009L;
    }
    public static int GL_MATRIX2_ARB() {
        return (int)35010L;
    }
    public static int GL_MATRIX3_ARB() {
        return (int)35011L;
    }
    public static int GL_MATRIX4_ARB() {
        return (int)35012L;
    }
    public static int GL_MATRIX5_ARB() {
        return (int)35013L;
    }
    public static int GL_MATRIX6_ARB() {
        return (int)35014L;
    }
    public static int GL_MATRIX7_ARB() {
        return (int)35015L;
    }
    public static int GL_MATRIX8_ARB() {
        return (int)35016L;
    }
    public static int GL_MATRIX9_ARB() {
        return (int)35017L;
    }
    public static int GL_MATRIX10_ARB() {
        return (int)35018L;
    }
    public static int GL_MATRIX11_ARB() {
        return (int)35019L;
    }
    public static int GL_MATRIX12_ARB() {
        return (int)35020L;
    }
    public static int GL_MATRIX13_ARB() {
        return (int)35021L;
    }
    public static int GL_MATRIX14_ARB() {
        return (int)35022L;
    }
    public static int GL_MATRIX15_ARB() {
        return (int)35023L;
    }
    public static int GL_MATRIX16_ARB() {
        return (int)35024L;
    }
    public static int GL_MATRIX17_ARB() {
        return (int)35025L;
    }
    public static int GL_MATRIX18_ARB() {
        return (int)35026L;
    }
    public static int GL_MATRIX19_ARB() {
        return (int)35027L;
    }
    public static int GL_MATRIX20_ARB() {
        return (int)35028L;
    }
    public static int GL_MATRIX21_ARB() {
        return (int)35029L;
    }
    public static int GL_MATRIX22_ARB() {
        return (int)35030L;
    }
    public static int GL_MATRIX23_ARB() {
        return (int)35031L;
    }
    public static int GL_MATRIX24_ARB() {
        return (int)35032L;
    }
    public static int GL_MATRIX25_ARB() {
        return (int)35033L;
    }
    public static int GL_MATRIX26_ARB() {
        return (int)35034L;
    }
    public static int GL_MATRIX27_ARB() {
        return (int)35035L;
    }
    public static int GL_MATRIX28_ARB() {
        return (int)35036L;
    }
    public static int GL_MATRIX29_ARB() {
        return (int)35037L;
    }
    public static int GL_MATRIX30_ARB() {
        return (int)35038L;
    }
    public static int GL_MATRIX31_ARB() {
        return (int)35039L;
    }
    public static int GL_COLOR_SUM_ARB() {
        return (int)33880L;
    }
    public static int GL_VERTEX_SHADER_ARB() {
        return (int)35633L;
    }
    public static int GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB() {
        return (int)35658L;
    }
    public static int GL_MAX_VARYING_FLOATS_ARB() {
        return (int)35659L;
    }
    public static int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB() {
        return (int)35661L;
    }
    public static int GL_OBJECT_ACTIVE_ATTRIBUTES_ARB() {
        return (int)35721L;
    }
    public static int GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB() {
        return (int)35722L;
    }
    public static int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB() {
        return (int)35660L;
    }
    public static int GL_ABGR_EXT() {
        return (int)32768L;
    }
    public static int GL_BGR_EXT() {
        return (int)32992L;
    }
    public static int GL_BGRA_EXT() {
        return (int)32993L;
    }
    public static int GL_MAX_VERTEX_BINDABLE_UNIFORMS_EXT() {
        return (int)36322L;
    }
    public static int GL_MAX_FRAGMENT_BINDABLE_UNIFORMS_EXT() {
        return (int)36323L;
    }
    public static int GL_MAX_GEOMETRY_BINDABLE_UNIFORMS_EXT() {
        return (int)36324L;
    }
    public static int GL_MAX_BINDABLE_UNIFORM_SIZE_EXT() {
        return (int)36333L;
    }
    public static int GL_UNIFORM_BUFFER_BINDING_EXT() {
        return (int)36335L;
    }
    public static int GL_UNIFORM_BUFFER_EXT() {
        return (int)36334L;
    }
    public static int GL_CONSTANT_COLOR_EXT() {
        return (int)32769L;
    }
    public static int GL_ONE_MINUS_CONSTANT_COLOR_EXT() {
        return (int)32770L;
    }
    public static int GL_CONSTANT_ALPHA_EXT() {
        return (int)32771L;
    }
    public static int GL_ONE_MINUS_CONSTANT_ALPHA_EXT() {
        return (int)32772L;
    }
    public static int GL_BLEND_COLOR_EXT() {
        return (int)32773L;
    }
    public static int GL_BLEND_EQUATION_RGB_EXT() {
        return (int)32777L;
    }
    public static int GL_BLEND_EQUATION_ALPHA_EXT() {
        return (int)34877L;
    }
    public static int GL_BLEND_DST_RGB_EXT() {
        return (int)32968L;
    }
    public static int GL_BLEND_SRC_RGB_EXT() {
        return (int)32969L;
    }
    public static int GL_BLEND_DST_ALPHA_EXT() {
        return (int)32970L;
    }
    public static int GL_BLEND_SRC_ALPHA_EXT() {
        return (int)32971L;
    }
    public static int GL_FUNC_ADD_EXT() {
        return (int)32774L;
    }
    public static int GL_MIN_EXT() {
        return (int)32775L;
    }
    public static int GL_MAX_EXT() {
        return (int)32776L;
    }
    public static int GL_BLEND_EQUATION_EXT() {
        return (int)32777L;
    }
    public static int GL_FUNC_SUBTRACT_EXT() {
        return (int)32778L;
    }
    public static int GL_FUNC_REVERSE_SUBTRACT_EXT() {
        return (int)32779L;
    }
    public static int GL_CLIP_VOLUME_CLIPPING_HINT_EXT() {
        return (int)33008L;
    }
    public static int GL_BUFFER_OBJECT_EXT() {
        return (int)37201L;
    }
    public static int GL_SHADER_OBJECT_EXT() {
        return (int)35656L;
    }
    public static int GL_PROGRAM_OBJECT_EXT() {
        return (int)35648L;
    }
    public static int GL_QUERY_OBJECT_EXT() {
        return (int)37203L;
    }
    public static int GL_VERTEX_ARRAY_OBJECT_EXT() {
        return (int)37204L;
    }
    public static int GL_SAMPLER() {
        return (int)33510L;
    }
    public static int GL_SYNC_OBJECT_APPLE() {
        return (int)35411L;
    }
    public static int GL_DEPTH_BOUNDS_TEST_EXT() {
        return (int)34960L;
    }
    public static int GL_DEPTH_BOUNDS_EXT() {
        return (int)34961L;
    }
    public static int GL_MAX_ELEMENTS_VERTICES_EXT() {
        return (int)33000L;
    }
    public static int GL_MAX_ELEMENTS_INDICES_EXT() {
        return (int)33001L;
    }
    public static int GL_FOG_COORDINATE_SOURCE_EXT() {
        return (int)33872L;
    }
    public static int GL_FOG_COORDINATE_EXT() {
        return (int)33873L;
    }
    public static int GL_FRAGMENT_DEPTH_EXT() {
        return (int)33874L;
    }
    public static int GL_CURRENT_FOG_COORDINATE_EXT() {
        return (int)33875L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_TYPE_EXT() {
        return (int)33876L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_STRIDE_EXT() {
        return (int)33877L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_POINTER_EXT() {
        return (int)33878L;
    }
    public static int GL_FOG_COORDINATE_ARRAY_EXT() {
        return (int)33879L;
    }
    public static int GL_READ_FRAMEBUFFER_EXT() {
        return (int)36008L;
    }
    public static int GL_DRAW_FRAMEBUFFER_EXT() {
        return (int)36009L;
    }
    public static int GL_DRAW_FRAMEBUFFER_BINDING_EXT() {
        return (int)36006L;
    }
    public static int GL_READ_FRAMEBUFFER_BINDING_EXT() {
        return (int)36010L;
    }
    public static int GL_RENDERBUFFER_SAMPLES_EXT() {
        return (int)36011L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT() {
        return (int)36182L;
    }
    public static int GL_MAX_SAMPLES_EXT() {
        return (int)36183L;
    }
    public static int GL_SCALED_RESOLVE_FASTEST_EXT() {
        return (int)37050L;
    }
    public static int GL_SCALED_RESOLVE_NICEST_EXT() {
        return (int)37051L;
    }
    public static int GL_FRAMEBUFFER_EXT() {
        return (int)36160L;
    }
    public static int GL_RENDERBUFFER_EXT() {
        return (int)36161L;
    }
    public static int GL_STENCIL_INDEX1_EXT() {
        return (int)36166L;
    }
    public static int GL_STENCIL_INDEX4_EXT() {
        return (int)36167L;
    }
    public static int GL_STENCIL_INDEX8_EXT() {
        return (int)36168L;
    }
    public static int GL_STENCIL_INDEX16_EXT() {
        return (int)36169L;
    }
    public static int GL_RENDERBUFFER_WIDTH_EXT() {
        return (int)36162L;
    }
    public static int GL_RENDERBUFFER_HEIGHT_EXT() {
        return (int)36163L;
    }
    public static int GL_RENDERBUFFER_INTERNAL_FORMAT_EXT() {
        return (int)36164L;
    }
    public static int GL_RENDERBUFFER_RED_SIZE_EXT() {
        return (int)36176L;
    }
    public static int GL_RENDERBUFFER_GREEN_SIZE_EXT() {
        return (int)36177L;
    }
    public static int GL_RENDERBUFFER_BLUE_SIZE_EXT() {
        return (int)36178L;
    }
    public static int GL_RENDERBUFFER_ALPHA_SIZE_EXT() {
        return (int)36179L;
    }
    public static int GL_RENDERBUFFER_DEPTH_SIZE_EXT() {
        return (int)36180L;
    }
    public static int GL_RENDERBUFFER_STENCIL_SIZE_EXT() {
        return (int)36181L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_EXT() {
        return (int)36048L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_EXT() {
        return (int)36049L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_EXT() {
        return (int)36050L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_EXT() {
        return (int)36051L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_EXT() {
        return (int)36052L;
    }
    public static int GL_COLOR_ATTACHMENT0_EXT() {
        return (int)36064L;
    }
    public static int GL_COLOR_ATTACHMENT1_EXT() {
        return (int)36065L;
    }
    public static int GL_COLOR_ATTACHMENT2_EXT() {
        return (int)36066L;
    }
    public static int GL_COLOR_ATTACHMENT3_EXT() {
        return (int)36067L;
    }
    public static int GL_COLOR_ATTACHMENT4_EXT() {
        return (int)36068L;
    }
    public static int GL_COLOR_ATTACHMENT5_EXT() {
        return (int)36069L;
    }
    public static int GL_COLOR_ATTACHMENT6_EXT() {
        return (int)36070L;
    }
    public static int GL_COLOR_ATTACHMENT7_EXT() {
        return (int)36071L;
    }
    public static int GL_COLOR_ATTACHMENT8_EXT() {
        return (int)36072L;
    }
    public static int GL_COLOR_ATTACHMENT9_EXT() {
        return (int)36073L;
    }
    public static int GL_COLOR_ATTACHMENT10_EXT() {
        return (int)36074L;
    }
    public static int GL_COLOR_ATTACHMENT11_EXT() {
        return (int)36075L;
    }
    public static int GL_COLOR_ATTACHMENT12_EXT() {
        return (int)36076L;
    }
    public static int GL_COLOR_ATTACHMENT13_EXT() {
        return (int)36077L;
    }
    public static int GL_COLOR_ATTACHMENT14_EXT() {
        return (int)36078L;
    }
    public static int GL_COLOR_ATTACHMENT15_EXT() {
        return (int)36079L;
    }
    public static int GL_DEPTH_ATTACHMENT_EXT() {
        return (int)36096L;
    }
    public static int GL_STENCIL_ATTACHMENT_EXT() {
        return (int)36128L;
    }
    public static int GL_FRAMEBUFFER_COMPLETE_EXT() {
        return (int)36053L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT() {
        return (int)36054L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT() {
        return (int)36055L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT() {
        return (int)36057L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT() {
        return (int)36058L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT() {
        return (int)36059L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT() {
        return (int)36060L;
    }
    public static int GL_FRAMEBUFFER_UNSUPPORTED_EXT() {
        return (int)36061L;
    }
    public static int GL_FRAMEBUFFER_BINDING_EXT() {
        return (int)36006L;
    }
    public static int GL_RENDERBUFFER_BINDING_EXT() {
        return (int)36007L;
    }
    public static int GL_MAX_COLOR_ATTACHMENTS_EXT() {
        return (int)36063L;
    }
    public static int GL_MAX_RENDERBUFFER_SIZE_EXT() {
        return (int)34024L;
    }
    public static int GL_INVALID_FRAMEBUFFER_OPERATION_EXT() {
        return (int)1286L;
    }
    public static int GL_FRAMEBUFFER_SRGB_EXT() {
        return (int)36281L;
    }
    public static int GL_FRAMEBUFFER_SRGB_CAPABLE_EXT() {
        return (int)36282L;
    }
    public static int GL_GEOMETRY_SHADER_EXT() {
        return (int)36313L;
    }
    public static int GL_GEOMETRY_VERTICES_OUT_EXT() {
        return (int)36314L;
    }
    public static int GL_GEOMETRY_INPUT_TYPE_EXT() {
        return (int)36315L;
    }
    public static int GL_GEOMETRY_OUTPUT_TYPE_EXT() {
        return (int)36316L;
    }
    public static int GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT() {
        return (int)35881L;
    }
    public static int GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT() {
        return (int)36317L;
    }
    public static int GL_MAX_VERTEX_VARYING_COMPONENTS_EXT() {
        return (int)36318L;
    }
    public static int GL_MAX_VARYING_COMPONENTS_EXT() {
        return (int)35659L;
    }
    public static int GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT() {
        return (int)36319L;
    }
    public static int GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT() {
        return (int)36320L;
    }
    public static int GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT() {
        return (int)36321L;
    }
    public static int GL_LINES_ADJACENCY_EXT() {
        return (int)10L;
    }
    public static int GL_LINE_STRIP_ADJACENCY_EXT() {
        return (int)11L;
    }
    public static int GL_TRIANGLES_ADJACENCY_EXT() {
        return (int)12L;
    }
    public static int GL_TRIANGLE_STRIP_ADJACENCY_EXT() {
        return (int)13L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT() {
        return (int)36264L;
    }
    public static int GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT() {
        return (int)36265L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT() {
        return (int)36263L;
    }
    public static int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT() {
        return (int)36052L;
    }
    public static int GL_PROGRAM_POINT_SIZE_EXT() {
        return (int)34370L;
    }
    public static int GL_VERTEX_ATTRIB_ARRAY_INTEGER_EXT() {
        return (int)35069L;
    }
    public static int GL_SAMPLER_1D_ARRAY_EXT() {
        return (int)36288L;
    }
    public static int GL_SAMPLER_2D_ARRAY_EXT() {
        return (int)36289L;
    }
    public static int GL_SAMPLER_BUFFER_EXT() {
        return (int)36290L;
    }
    public static int GL_SAMPLER_1D_ARRAY_SHADOW_EXT() {
        return (int)36291L;
    }
    public static int GL_SAMPLER_2D_ARRAY_SHADOW_EXT() {
        return (int)36292L;
    }
    public static int GL_SAMPLER_CUBE_SHADOW_EXT() {
        return (int)36293L;
    }
    public static int GL_UNSIGNED_INT_VEC2_EXT() {
        return (int)36294L;
    }
    public static int GL_UNSIGNED_INT_VEC3_EXT() {
        return (int)36295L;
    }
    public static int GL_UNSIGNED_INT_VEC4_EXT() {
        return (int)36296L;
    }
    public static int GL_INT_SAMPLER_1D_EXT() {
        return (int)36297L;
    }
    public static int GL_INT_SAMPLER_2D_EXT() {
        return (int)36298L;
    }
    public static int GL_INT_SAMPLER_3D_EXT() {
        return (int)36299L;
    }
    public static int GL_INT_SAMPLER_CUBE_EXT() {
        return (int)36300L;
    }
    public static int GL_INT_SAMPLER_2D_RECT_EXT() {
        return (int)36301L;
    }
    public static int GL_INT_SAMPLER_1D_ARRAY_EXT() {
        return (int)36302L;
    }
    public static int GL_INT_SAMPLER_2D_ARRAY_EXT() {
        return (int)36303L;
    }
    public static int GL_INT_SAMPLER_BUFFER_EXT() {
        return (int)36304L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_1D_EXT() {
        return (int)36305L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_2D_EXT() {
        return (int)36306L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_3D_EXT() {
        return (int)36307L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_CUBE_EXT() {
        return (int)36308L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_2D_RECT_EXT() {
        return (int)36309L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_1D_ARRAY_EXT() {
        return (int)36310L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY_EXT() {
        return (int)36311L;
    }
    public static int GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT() {
        return (int)36312L;
    }
    public static int GL_MIN_PROGRAM_TEXEL_OFFSET_EXT() {
        return (int)35076L;
    }
    public static int GL_MAX_PROGRAM_TEXEL_OFFSET_EXT() {
        return (int)35077L;
    }
    public static int GL_DEPTH_STENCIL_EXT() {
        return (int)34041L;
    }
    public static int GL_UNSIGNED_INT_24_8_EXT() {
        return (int)34042L;
    }
    public static int GL_DEPTH24_STENCIL8_EXT() {
        return (int)35056L;
    }
    public static int GL_TEXTURE_STENCIL_SIZE_EXT() {
        return (int)35057L;
    }
    public static int GL_R11F_G11F_B10F_EXT() {
        return (int)35898L;
    }
    public static int GL_UNSIGNED_INT_10F_11F_11F_REV_EXT() {
        return (int)35899L;
    }
    public static int GL_RGBA_SIGNED_COMPONENTS_EXT() {
        return (int)35900L;
    }
    public static int GL_FIRST_VERTEX_CONVENTION_EXT() {
        return (int)36429L;
    }
    public static int GL_LAST_VERTEX_CONVENTION_EXT() {
        return (int)36430L;
    }
    public static int GL_PROVOKING_VERTEX_EXT() {
        return (int)36431L;
    }
    public static int GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION_EXT() {
        return (int)36428L;
    }
    public static int GL_RESCALE_NORMAL_EXT() {
        return (int)32826L;
    }
    public static int GL_COLOR_SUM_EXT() {
        return (int)33880L;
    }
    public static int GL_CURRENT_SECONDARY_COLOR_EXT() {
        return (int)33881L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_SIZE_EXT() {
        return (int)33882L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_TYPE_EXT() {
        return (int)33883L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_STRIDE_EXT() {
        return (int)33884L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_POINTER_EXT() {
        return (int)33885L;
    }
    public static int GL_SECONDARY_COLOR_ARRAY_EXT() {
        return (int)33886L;
    }
    public static int GL_LIGHT_MODEL_COLOR_CONTROL_EXT() {
        return (int)33272L;
    }
    public static int GL_SINGLE_COLOR_EXT() {
        return (int)33273L;
    }
    public static int GL_SEPARATE_SPECULAR_COLOR_EXT() {
        return (int)33274L;
    }
    public static int GL_STENCIL_TEST_TWO_SIDE_EXT() {
        return (int)35088L;
    }
    public static int GL_ACTIVE_STENCIL_FACE_EXT() {
        return (int)35089L;
    }
    public static int GL_INCR_WRAP_EXT() {
        return (int)34055L;
    }
    public static int GL_DECR_WRAP_EXT() {
        return (int)34056L;
    }
    public static int GL_TEXTURE_1D_ARRAY_EXT() {
        return (int)35864L;
    }
    public static int GL_PROXY_TEXTURE_1D_ARRAY_EXT() {
        return (int)35865L;
    }
    public static int GL_TEXTURE_2D_ARRAY_EXT() {
        return (int)35866L;
    }
    public static int GL_PROXY_TEXTURE_2D_ARRAY_EXT() {
        return (int)35867L;
    }
    public static int GL_TEXTURE_BINDING_1D_ARRAY_EXT() {
        return (int)35868L;
    }
    public static int GL_TEXTURE_BINDING_2D_ARRAY_EXT() {
        return (int)35869L;
    }
    public static int GL_MAX_ARRAY_TEXTURE_LAYERS_EXT() {
        return (int)35071L;
    }
    public static int GL_COMPARE_REF_DEPTH_TO_TEXTURE_EXT() {
        return (int)34894L;
    }
    public static int GL_COMPRESSED_RGB_S3TC_DXT1_EXT() {
        return (int)33776L;
    }
    public static int GL_COMPRESSED_RGBA_S3TC_DXT1_EXT() {
        return (int)33777L;
    }
    public static int GL_COMPRESSED_RGBA_S3TC_DXT3_EXT() {
        return (int)33778L;
    }
    public static int GL_COMPRESSED_RGBA_S3TC_DXT5_EXT() {
        return (int)33779L;
    }
    public static int GL_TEXTURE_MAX_ANISOTROPY_EXT() {
        return (int)34046L;
    }
    public static int GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT() {
        return (int)34047L;
    }
    public static int GL_RGBA_INTEGER_MODE_EXT() {
        return (int)36254L;
    }
    public static int GL_RGBA32UI_EXT() {
        return (int)36208L;
    }
    public static int GL_RGB32UI_EXT() {
        return (int)36209L;
    }
    public static int GL_ALPHA32UI_EXT() {
        return (int)36210L;
    }
    public static int GL_INTENSITY32UI_EXT() {
        return (int)36211L;
    }
    public static int GL_LUMINANCE32UI_EXT() {
        return (int)36212L;
    }
    public static int GL_LUMINANCE_ALPHA32UI_EXT() {
        return (int)36213L;
    }
    public static int GL_RGBA16UI_EXT() {
        return (int)36214L;
    }
    public static int GL_RGB16UI_EXT() {
        return (int)36215L;
    }
    public static int GL_ALPHA16UI_EXT() {
        return (int)36216L;
    }
    public static int GL_INTENSITY16UI_EXT() {
        return (int)36217L;
    }
    public static int GL_LUMINANCE16UI_EXT() {
        return (int)36218L;
    }
    public static int GL_LUMINANCE_ALPHA16UI_EXT() {
        return (int)36219L;
    }
    public static int GL_RGBA8UI_EXT() {
        return (int)36220L;
    }
    public static int GL_RGB8UI_EXT() {
        return (int)36221L;
    }
    public static int GL_ALPHA8UI_EXT() {
        return (int)36222L;
    }
    public static int GL_INTENSITY8UI_EXT() {
        return (int)36223L;
    }
    public static int GL_LUMINANCE8UI_EXT() {
        return (int)36224L;
    }
    public static int GL_LUMINANCE_ALPHA8UI_EXT() {
        return (int)36225L;
    }
    public static int GL_RGBA32I_EXT() {
        return (int)36226L;
    }
    public static int GL_RGB32I_EXT() {
        return (int)36227L;
    }
    public static int GL_ALPHA32I_EXT() {
        return (int)36228L;
    }
    public static int GL_INTENSITY32I_EXT() {
        return (int)36229L;
    }
    public static int GL_LUMINANCE32I_EXT() {
        return (int)36230L;
    }
    public static int GL_LUMINANCE_ALPHA32I_EXT() {
        return (int)36231L;
    }
    public static int GL_RGBA16I_EXT() {
        return (int)36232L;
    }
    public static int GL_RGB16I_EXT() {
        return (int)36233L;
    }
    public static int GL_ALPHA16I_EXT() {
        return (int)36234L;
    }
    public static int GL_INTENSITY16I_EXT() {
        return (int)36235L;
    }
    public static int GL_LUMINANCE16I_EXT() {
        return (int)36236L;
    }
    public static int GL_LUMINANCE_ALPHA16I_EXT() {
        return (int)36237L;
    }
    public static int GL_RGBA8I_EXT() {
        return (int)36238L;
    }
    public static int GL_RGB8I_EXT() {
        return (int)36239L;
    }
    public static int GL_ALPHA8I_EXT() {
        return (int)36240L;
    }
    public static int GL_INTENSITY8I_EXT() {
        return (int)36241L;
    }
    public static int GL_LUMINANCE8I_EXT() {
        return (int)36242L;
    }
    public static int GL_LUMINANCE_ALPHA8I_EXT() {
        return (int)36243L;
    }
    public static int GL_RED_INTEGER_EXT() {
        return (int)36244L;
    }
    public static int GL_GREEN_INTEGER_EXT() {
        return (int)36245L;
    }
    public static int GL_BLUE_INTEGER_EXT() {
        return (int)36246L;
    }
    public static int GL_ALPHA_INTEGER_EXT() {
        return (int)36247L;
    }
    public static int GL_RGB_INTEGER_EXT() {
        return (int)36248L;
    }
    public static int GL_RGBA_INTEGER_EXT() {
        return (int)36249L;
    }
    public static int GL_BGR_INTEGER_EXT() {
        return (int)36250L;
    }
    public static int GL_BGRA_INTEGER_EXT() {
        return (int)36251L;
    }
    public static int GL_LUMINANCE_INTEGER_EXT() {
        return (int)36252L;
    }
    public static int GL_LUMINANCE_ALPHA_INTEGER_EXT() {
        return (int)36253L;
    }
    public static int GL_MAX_TEXTURE_LOD_BIAS_EXT() {
        return (int)34045L;
    }
    public static int GL_TEXTURE_FILTER_CONTROL_EXT() {
        return (int)34048L;
    }
    public static int GL_TEXTURE_LOD_BIAS_EXT() {
        return (int)34049L;
    }
    public static int GL_MIRROR_CLAMP_EXT() {
        return (int)34626L;
    }
    public static int GL_MIRROR_CLAMP_TO_EDGE_EXT() {
        return (int)34627L;
    }
    public static int GL_MIRROR_CLAMP_TO_BORDER_EXT() {
        return (int)35090L;
    }
    public static int GL_TEXTURE_RECTANGLE_EXT() {
        return (int)34037L;
    }
    public static int GL_TEXTURE_BINDING_RECTANGLE_EXT() {
        return (int)34038L;
    }
    public static int GL_PROXY_TEXTURE_RECTANGLE_EXT() {
        return (int)34039L;
    }
    public static int GL_MAX_RECTANGLE_TEXTURE_SIZE_EXT() {
        return (int)34040L;
    }
}


