// Generated by jextract

package opengl.macos.v10_15_3;

import java.lang.invoke.MethodHandle;

import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$168 {

    static final FunctionDescriptor gluLoadSamplingMatrices$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluLoadSamplingMatrices$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluLoadSamplingMatrices",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$168.gluLoadSamplingMatrices$FUNC, false
    );
    static final FunctionDescriptor gluLookAt$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle gluLookAt$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluLookAt",
        "(DDDDDDDDD)V",
        constants$168.gluLookAt$FUNC, false
    );
    static final FunctionDescriptor gluNewNurbsRenderer$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle gluNewNurbsRenderer$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNewNurbsRenderer",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$168.gluNewNurbsRenderer$FUNC, false
    );
    static final FunctionDescriptor gluNewQuadric$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle gluNewQuadric$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNewQuadric",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$168.gluNewQuadric$FUNC, false
    );
    static final FunctionDescriptor gluNewTess$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle gluNewTess$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNewTess",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$168.gluNewTess$FUNC, false
    );
    static final FunctionDescriptor gluNextContour$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT
    );
    static final MethodHandle gluNextContour$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluNextContour",
        "(Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$168.gluNextContour$FUNC, false
    );
}


