// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$907 {

    static final FunctionDescriptor PFNGLTAGSAMPLEBUFFERSGIXPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLTAGSAMPLEBUFFERSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$907.PFNGLTAGSAMPLEBUFFERSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLORTABLESGIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOLORTABLESGIPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$907.PFNGLCOLORTABLESGIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLORTABLEPARAMETERFVSGIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOLORTABLEPARAMETERFVSGIPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$907.PFNGLCOLORTABLEPARAMETERFVSGIPROC$FUNC, false
    );
}


