// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$340 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4I64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4I64VARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$340.PFNGLPROGRAMUNIFORM4I64VARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJ)V",
        constants$340.PFNGLPROGRAMUNIFORM1UI64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM2UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM2UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJ)V",
        constants$340.PFNGLPROGRAMUNIFORM2UI64ARBPROC$FUNC, false
    );
}


