// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$605 {

    static final FunctionDescriptor PFNGLVERTEXARRAYVERTEXATTRIBIOFFSETEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXARRAYVERTEXATTRIBIOFFSETEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIJ)V",
        constants$605.PFNGLVERTEXARRAYVERTEXATTRIBIOFFSETEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLENABLEVERTEXARRAYEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLENABLEVERTEXARRAYEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$605.PFNGLENABLEVERTEXARRAYEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDISABLEVERTEXARRAYEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDISABLEVERTEXARRAYEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$605.PFNGLDISABLEVERTEXARRAYEXTPROC$FUNC, false
    );
}


