// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$435 {

    static final FunctionDescriptor PFNGLMULTTRANSPOSEMATRIXXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLMULTTRANSPOSEMATRIXXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$435.PFNGLMULTTRANSPOSEMATRIXXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD1XOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLMULTITEXCOORD1XOESPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$435.PFNGLMULTITEXCOORD1XOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTITEXCOORD1XVOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMULTITEXCOORD1XVOESPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$435.PFNGLMULTITEXCOORD1XVOESPROC$FUNC, false
    );
}


