// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$668 {

    static final FunctionDescriptor PFNGLTEXBUFFEREXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXBUFFEREXTPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$668.PFNGLTEXBUFFEREXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXPARAMETERIIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLTEXPARAMETERIIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$668.PFNGLTEXPARAMETERIIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXPARAMETERIUIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLTEXPARAMETERIUIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$668.PFNGLTEXPARAMETERIUIVEXTPROC$FUNC, false
    );
}


