// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$669 {

    static final FunctionDescriptor PFNGLGETTEXPARAMETERIIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXPARAMETERIIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$669.PFNGLGETTEXPARAMETERIIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETTEXPARAMETERIUIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXPARAMETERIUIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$669.PFNGLGETTEXPARAMETERIUIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCLEARCOLORIIEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCLEARCOLORIIEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$669.PFNGLCLEARCOLORIIEXTPROC$FUNC, false
    );
}


