// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$774 {

    static final FunctionDescriptor PFNGLSECONDARYCOLOR3HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle PFNGLSECONDARYCOLOR3HNVPROC$MH = RuntimeHelper.downcallHandle(
        "(SSS)V",
        constants$774.PFNGLSECONDARYCOLOR3HNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSECONDARYCOLOR3HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLSECONDARYCOLOR3HVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$774.PFNGLSECONDARYCOLOR3HVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXWEIGHTHNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT
    );
    static final MethodHandle PFNGLVERTEXWEIGHTHNVPROC$MH = RuntimeHelper.downcallHandle(
        "(S)V",
        constants$774.PFNGLVERTEXWEIGHTHNVPROC$FUNC, false
    );
}


