// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$652 {

    static final FunctionDescriptor PFNGLGETPIXELTRANSFORMPARAMETERIVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPIXELTRANSFORMPARAMETERIVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$652.PFNGLGETPIXELTRANSFORMPARAMETERIVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPIXELTRANSFORMPARAMETERFVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPIXELTRANSFORMPARAMETERFVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$652.PFNGLGETPIXELTRANSFORMPARAMETERFVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPOINTPARAMETERFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLPOINTPARAMETERFEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IF)V",
        constants$652.PFNGLPOINTPARAMETERFEXTPROC$FUNC, false
    );
}


