// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$219 {

    static final FunctionDescriptor PFNGLGETQUERYINDEXEDIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETQUERYINDEXEDIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$219.PFNGLGETQUERYINDEXEDIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLRELEASESHADERCOMPILERPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLRELEASESHADERCOMPILERPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$219.PFNGLRELEASESHADERCOMPILERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSHADERBINARYPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle PFNGLSHADERBINARYPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)V",
        constants$219.PFNGLSHADERBINARYPROC$FUNC, false
    );
}


