// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$987 {

    static final FunctionDescriptor getloadavg$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle getloadavg$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "getloadavg",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$987.getloadavg$FUNC, false
    );
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
    static final MemorySegment __FD_ZERO_STOS$SEGMENT = CLinker.toCString("stosq", ResourceScope.newImplicitScope());
}


