// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$819 {

    static final FunctionDescriptor PFNGLSCISSOREXCLUSIVENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLSCISSOREXCLUSIVENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$819.PFNGLSCISSOREXCLUSIVENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSCISSOREXCLUSIVEARRAYVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLSCISSOREXCLUSIVEARRAYVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$819.PFNGLSCISSOREXCLUSIVEARRAYVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMAKEBUFFERRESIDENTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLMAKEBUFFERRESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$819.PFNGLMAKEBUFFERRESIDENTNVPROC$FUNC, false
    );
}


