// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$817 {

    static final FunctionDescriptor PFNGLGETFINALCOMBINERINPUTPARAMETERIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETFINALCOMBINERINPUTPARAMETERIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$817.PFNGLGETFINALCOMBINERINPUTPARAMETERIVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOMBINERSTAGEPARAMETERFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOMBINERSTAGEPARAMETERFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$817.PFNGLCOMBINERSTAGEPARAMETERFVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOMBINERSTAGEPARAMETERFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETCOMBINERSTAGEPARAMETERFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$817.PFNGLGETCOMBINERSTAGEPARAMETERFVNVPROC$FUNC, false
    );
}


