// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$475 {

    static final FunctionDescriptor PFNGLELEMENTPOINTERAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLELEMENTPOINTERAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$475.PFNGLELEMENTPOINTERAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWELEMENTARRAYAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDRAWELEMENTARRAYAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$475.PFNGLDRAWELEMENTARRAYAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWRANGEELEMENTARRAYAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDRAWRANGEELEMENTARRAYAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$475.PFNGLDRAWRANGEELEMENTARRAYAPPLEPROC$FUNC, false
    );
}


