// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$705 {

    static final FunctionDescriptor PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$705.PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSYNCTEXTUREINTELPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLSYNCTEXTUREINTELPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$705.PFNGLSYNCTEXTUREINTELPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNMAPTEXTURE2DINTELPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLUNMAPTEXTURE2DINTELPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$705.PFNGLUNMAPTEXTURE2DINTELPROC$FUNC, false
    );
}


