// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$884 {

    static final FunctionDescriptor PFNGLGETDETAILTEXFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETDETAILTEXFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$884.PFNGLGETDETAILTEXFUNCSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLFOGFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$884.PFNGLFOGFUNCSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETFOGFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLGETFOGFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$884.PFNGLGETFOGFUNCSGISPROC$FUNC, false
    );
}


