// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$834 {

    static final FunctionDescriptor PFNGLPAUSETRANSFORMFEEDBACKNVPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLPAUSETRANSFORMFEEDBACKNVPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$834.PFNGLPAUSETRANSFORMFEEDBACKNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLRESUMETRANSFORMFEEDBACKNVPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLRESUMETRANSFORMFEEDBACKNVPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$834.PFNGLRESUMETRANSFORMFEEDBACKNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWTRANSFORMFEEDBACKNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDRAWTRANSFORMFEEDBACKNVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$834.PFNGLDRAWTRANSFORMFEEDBACKNVPROC$FUNC, false
    );
}


