// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$854 {

    static final FunctionDescriptor PFNGLGETVERTEXATTRIBPOINTERVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBPOINTERVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$854.PFNGLGETVERTEXATTRIBPOINTERVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISPROGRAMNVPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT
    );
    static final MethodHandle PFNGLISPROGRAMNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)B",
        constants$854.PFNGLISPROGRAMNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLLOADPROGRAMNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLLOADPROGRAMNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$854.PFNGLLOADPROGRAMNVPROC$FUNC, false
    );
}


