// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$881 {

    static final FunctionDescriptor PFNGLGETVIDEOCAPTURESTREAMDVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVIDEOCAPTURESTREAMDVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$881.PFNGLGETVIDEOCAPTURESTREAMDVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVIDEOCAPTURENVPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle PFNGLVIDEOCAPTURENVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$881.PFNGLVIDEOCAPTURENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVIDEOCAPTURESTREAMPARAMETERIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVIDEOCAPTURESTREAMPARAMETERIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$881.PFNGLVIDEOCAPTURESTREAMPARAMETERIVNVPROC$FUNC, false
    );
}


