// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$290 {

    static final FunctionDescriptor PFNGLCOPYTEXTURESUBIMAGE2DPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYTEXTURESUBIMAGE2DPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIII)V",
        constants$290.PFNGLCOPYTEXTURESUBIMAGE2DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYTEXTURESUBIMAGE3DPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYTEXTURESUBIMAGE3DPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIII)V",
        constants$290.PFNGLCOPYTEXTURESUBIMAGE3DPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREPARAMETERFPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLTEXTUREPARAMETERFPROC$MH = RuntimeHelper.downcallHandle(
        "(IIF)V",
        constants$290.PFNGLTEXTUREPARAMETERFPROC$FUNC, false
    );
}


