// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$227 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1UIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1UIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$227.PFNGLPROGRAMUNIFORM1UIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM2IPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM2IPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$227.PFNGLPROGRAMUNIFORM2IPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM2IVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM2IVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$227.PFNGLPROGRAMUNIFORM2IVPROC$FUNC, false
    );
}


