// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$871 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBI1IEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI1IEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$871.PFNGLVERTEXATTRIBI1IEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBI2IEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI2IEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$871.PFNGLVERTEXATTRIBI2IEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBI3IEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXATTRIBI3IEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$871.PFNGLVERTEXATTRIBI3IEXTPROC$FUNC, false
    );
}


