// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$784 {

    static final FunctionDescriptor PFNGLBEGINOCCLUSIONQUERYNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLBEGINOCCLUSIONQUERYNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$784.PFNGLBEGINOCCLUSIONQUERYNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLENDOCCLUSIONQUERYNVPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLENDOCCLUSIONQUERYNVPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$784.PFNGLENDOCCLUSIONQUERYNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETOCCLUSIONQUERYIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETOCCLUSIONQUERYIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$784.PFNGLGETOCCLUSIONQUERYIVNVPROC$FUNC, false
    );
}


