// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$827 {

    static final FunctionDescriptor PFNGLTEXIMAGE3DMULTISAMPLECOVERAGENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_CHAR
    );
    static final MethodHandle PFNGLTEXIMAGE3DMULTISAMPLECOVERAGENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIB)V",
        constants$827.PFNGLTEXIMAGE3DMULTISAMPLECOVERAGENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREIMAGE2DMULTISAMPLENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_CHAR
    );
    static final MethodHandle PFNGLTEXTUREIMAGE2DMULTISAMPLENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIB)V",
        constants$827.PFNGLTEXTUREIMAGE2DMULTISAMPLENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTUREIMAGE3DMULTISAMPLENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_CHAR
    );
    static final MethodHandle PFNGLTEXTUREIMAGE3DMULTISAMPLENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIB)V",
        constants$827.PFNGLTEXTUREIMAGE3DMULTISAMPLENVPROC$FUNC, false
    );
}


