// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$279 {

    static final FunctionDescriptor PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$279.PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$279.PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$279.PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC$FUNC, false
    );
}


