// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$775 {

    static final FunctionDescriptor PFNGLVERTEXWEIGHTHVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXWEIGHTHVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$775.PFNGLVERTEXWEIGHTHVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB1HNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_SHORT
    );
    static final MethodHandle PFNGLVERTEXATTRIB1HNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IS)V",
        constants$775.PFNGLVERTEXATTRIB1HNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB1HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB1HVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$775.PFNGLVERTEXATTRIB1HVNVPROC$FUNC, false
    );
}


