// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$890 {

    static final FunctionDescriptor PFNGLGETTEXFILTERFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXFILTERFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$890.PFNGLGETTEXFILTERFUNCSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXFILTERFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLTEXFILTERFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$890.PFNGLTEXFILTERFUNCSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLASYNCMARKERSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLASYNCMARKERSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$890.PFNGLASYNCMARKERSGIXPROC$FUNC, false
    );
}


