// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$820 {

    static final FunctionDescriptor PFNGLMAKEBUFFERNONRESIDENTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLMAKEBUFFERNONRESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$820.PFNGLMAKEBUFFERNONRESIDENTNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISBUFFERRESIDENTNVPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT
    );
    static final MethodHandle PFNGLISBUFFERRESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)B",
        constants$820.PFNGLISBUFFERRESIDENTNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMAKENAMEDBUFFERRESIDENTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLMAKENAMEDBUFFERRESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$820.PFNGLMAKENAMEDBUFFERRESIDENTNVPROC$FUNC, false
    );
}


