// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$260 {

    static final FunctionDescriptor PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)I",
        constants$260.PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSHADERSTORAGEBLOCKBINDINGPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLSHADERSTORAGEBLOCKBINDINGPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$260.PFNGLSHADERSTORAGEBLOCKBINDINGPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXBUFFERRANGEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLTEXBUFFERRANGEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIJJ)V",
        constants$260.PFNGLTEXBUFFERRANGEPROC$FUNC, false
    );
}


