// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$528 {

    static final FunctionDescriptor PFNGLBINORMAL3BVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLBINORMAL3BVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$528.PFNGLBINORMAL3BVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBINORMAL3DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLBINORMAL3DEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(DDD)V",
        constants$528.PFNGLBINORMAL3DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBINORMAL3DVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLBINORMAL3DVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$528.PFNGLBINORMAL3DVEXTPROC$FUNC, false
    );
}


