// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$518 {

    static final FunctionDescriptor PFNGLBLENDFUNCSEPARATEEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLBLENDFUNCSEPARATEEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$518.PFNGLBLENDFUNCSEPARATEEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBLENDEQUATIONEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLBLENDEQUATIONEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$518.PFNGLBLENDEQUATIONEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLORSUBTABLEEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOLORSUBTABLEEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$518.PFNGLCOLORSUBTABLEEXTPROC$FUNC, false
    );
}


