// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$671 {

    static final FunctionDescriptor PFNGLDELETETEXTURESEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDELETETEXTURESEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$671.PFNGLDELETETEXTURESEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGENTEXTURESEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGENTEXTURESEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$671.PFNGLGENTEXTURESEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISTEXTUREEXTPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT
    );
    static final MethodHandle PFNGLISTEXTUREEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)B",
        constants$671.PFNGLISTEXTUREEXTPROC$FUNC, false
    );
}


