// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$912 {

    static final FunctionDescriptor PFNGLGLOBALALPHAFACTORUSSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT
    );
    static final MethodHandle PFNGLGLOBALALPHAFACTORUSSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(S)V",
        constants$912.PFNGLGLOBALALPHAFACTORUSSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGLOBALALPHAFACTORUISUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLGLOBALALPHAFACTORUISUNPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$912.PFNGLGLOBALALPHAFACTORUISUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWMESHARRAYSSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDRAWMESHARRAYSSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$912.PFNGLDRAWMESHARRAYSSUNPROC$FUNC, false
    );
}


