// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$639 {

    static final FunctionDescriptor PFNGLINDEXFUNCEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLINDEXFUNCEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IF)V",
        constants$639.PFNGLINDEXFUNCEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLINDEXMATERIALEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLINDEXMATERIALEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$639.PFNGLINDEXMATERIALEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLAPPLYTEXTUREEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLAPPLYTEXTUREEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$639.PFNGLAPPLYTEXTUREEXTPROC$FUNC, false
    );
}


