// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$483 {

    static final FunctionDescriptor PFNGLVERTEXARRAYRANGEAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXARRAYRANGEAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$483.PFNGLVERTEXARRAYRANGEAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFLUSHVERTEXARRAYRANGEAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLFLUSHVERTEXARRAYRANGEAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$483.PFNGLFLUSHVERTEXARRAYRANGEAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXARRAYPARAMETERIAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXARRAYPARAMETERIAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$483.PFNGLVERTEXARRAYPARAMETERIAPPLEPROC$FUNC, false
    );
}


