// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$842 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBL1UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL1UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)V",
        constants$842.PFNGLVERTEXATTRIBL1UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL2UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL2UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$842.PFNGLVERTEXATTRIBL2UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL3UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL3UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJ)V",
        constants$842.PFNGLVERTEXATTRIBL3UI64NVPROC$FUNC, false
    );
}


