// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$465 {

    static final FunctionDescriptor PFNGLPROGRAMUNIFORM3UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM3UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJJ)V",
        constants$465.PFNGLPROGRAMUNIFORM3UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM4UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM4UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJJJ)V",
        constants$465.PFNGLPROGRAMUNIFORM4UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1UI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1UI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$465.PFNGLPROGRAMUNIFORM1UI64VNVPROC$FUNC, false
    );
}


