// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$686 {

    static final FunctionDescriptor PFNGLGENSYMBOLSEXTPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLGENSYMBOLSEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)I",
        constants$686.PFNGLGENSYMBOLSEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSETINVARIANTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLSETINVARIANTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$686.PFNGLSETINVARIANTEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSETLOCALCONSTANTEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLSETLOCALCONSTANTEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$686.PFNGLSETLOCALCONSTANTEXTPROC$FUNC, false
    );
}


