// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$785 {

    static final FunctionDescriptor PFNGLGETOCCLUSIONQUERYUIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETOCCLUSIONQUERYUIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$785.PFNGLGETOCCLUSIONQUERYUIVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$785.PFNGLPROGRAMBUFFERPARAMETERSFVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$785.PFNGLPROGRAMBUFFERPARAMETERSIIVNVPROC$FUNC, false
    );
}


