// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$223 {

    static final FunctionDescriptor PFNGLBINDPROGRAMPIPELINEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLBINDPROGRAMPIPELINEPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$223.PFNGLBINDPROGRAMPIPELINEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDELETEPROGRAMPIPELINESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDELETEPROGRAMPIPELINESPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$223.PFNGLDELETEPROGRAMPIPELINESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGENPROGRAMPIPELINESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGENPROGRAMPIPELINESPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$223.PFNGLGENPROGRAMPIPELINESPROC$FUNC, false
    );
}


