// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$513 {

    static final FunctionDescriptor PFNGLNORMALSTREAM3IVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLNORMALSTREAM3IVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$513.PFNGLNORMALSTREAM3IVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMALSTREAM3FATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLNORMALSTREAM3FATIPROC$MH = RuntimeHelper.downcallHandle(
        "(IFFF)V",
        constants$513.PFNGLNORMALSTREAM3FATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMALSTREAM3FVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLNORMALSTREAM3FVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$513.PFNGLNORMALSTREAM3FVATIPROC$FUNC, false
    );
}


