// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$390 {

    static final FunctionDescriptor PFNGLVERTEXATTRIB3FVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB3FVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$390.PFNGLVERTEXATTRIB3FVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3SARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_SHORT,
        C_SHORT,
        C_SHORT
    );
    static final MethodHandle PFNGLVERTEXATTRIB3SARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ISSS)V",
        constants$390.PFNGLVERTEXATTRIB3SARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3SVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB3SVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$390.PFNGLVERTEXATTRIB3SVARBPROC$FUNC, false
    );
}


