// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface glutCreateMenu$callback {

    void apply(int x0);
    static MemoryAddress allocate(glutCreateMenu$callback fi) {
        return RuntimeHelper.upcallStub(glutCreateMenu$callback.class, fi, constants$947.glutCreateMenu$callback$FUNC, "(I)V");
    }
    static MemoryAddress allocate(glutCreateMenu$callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(glutCreateMenu$callback.class, fi, constants$947.glutCreateMenu$callback$FUNC, "(I)V", scope);
    }
    static glutCreateMenu$callback ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$947.glutCreateMenu$callback$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


