// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLUNMAPNAMEDBUFFEREXTPROC {

    byte apply(int x0);
    static MemoryAddress allocate(PFNGLUNMAPNAMEDBUFFEREXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLUNMAPNAMEDBUFFEREXTPROC.class, fi, constants$571.PFNGLUNMAPNAMEDBUFFEREXTPROC$FUNC, "(I)B");
    }
    static MemoryAddress allocate(PFNGLUNMAPNAMEDBUFFEREXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUNMAPNAMEDBUFFEREXTPROC.class, fi, constants$571.PFNGLUNMAPNAMEDBUFFEREXTPROC$FUNC, "(I)B", scope);
    }
    static PFNGLUNMAPNAMEDBUFFEREXTPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                return (byte)constants$571.PFNGLUNMAPNAMEDBUFFEREXTPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


