// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC {

    void apply(int x0, int x1, jdk.incubator.foreign.MemoryAddress x2);
    static MemoryAddress allocate(PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC.class, fi, constants$711.PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC$FUNC, "(IILjdk/incubator/foreign/MemoryAddress;)V");
    }
    static MemoryAddress allocate(PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC.class, fi, constants$711.PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC$FUNC, "(IILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC ofAddress(MemoryAddress addr) {
        return (int x0, int x1, jdk.incubator.foreign.MemoryAddress x2) -> {
            try {
                constants$711.PFNGLGETFRAMEBUFFERPARAMETERIVMESAPROC$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


