// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC {

    void apply(long x0, int x1, int x2);
    static MemoryAddress allocate(PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC.class, fi, constants$782.PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC$FUNC, "(JII)V");
    }
    static MemoryAddress allocate(PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC.class, fi, constants$782.PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC$FUNC, "(JII)V", scope);
    }
    static PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC ofAddress(MemoryAddress addr) {
        return (long x0, int x1, int x2) -> {
            try {
                constants$782.PFNGLMULTIDRAWMESHTASKSINDIRECTNVPROC$MH.invokeExact((Addressable)addr, x0, x1, x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


