// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLUPLOADGPUMASKNVXPROC {

    void apply(int x0);
    static MemoryAddress allocate(PFNGLUPLOADGPUMASKNVXPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLUPLOADGPUMASKNVXPROC.class, fi, constants$720.PFNGLUPLOADGPUMASKNVXPROC$FUNC, "(I)V");
    }
    static MemoryAddress allocate(PFNGLUPLOADGPUMASKNVXPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLUPLOADGPUMASKNVXPROC.class, fi, constants$720.PFNGLUPLOADGPUMASKNVXPROC$FUNC, "(I)V", scope);
    }
    static PFNGLUPLOADGPUMASKNVXPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$720.PFNGLUPLOADGPUMASKNVXPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


