// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLGLOBALALPHAFACTORUBSUNPROC {

    void apply(byte x0);
    static MemoryAddress allocate(PFNGLGLOBALALPHAFACTORUBSUNPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLGLOBALALPHAFACTORUBSUNPROC.class, fi, constants$911.PFNGLGLOBALALPHAFACTORUBSUNPROC$FUNC, "(B)V");
    }
    static MemoryAddress allocate(PFNGLGLOBALALPHAFACTORUBSUNPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLGLOBALALPHAFACTORUBSUNPROC.class, fi, constants$911.PFNGLGLOBALALPHAFACTORUBSUNPROC$FUNC, "(B)V", scope);
    }
    static PFNGLGLOBALALPHAFACTORUBSUNPROC ofAddress(MemoryAddress addr) {
        return (byte x0) -> {
            try {
                constants$911.PFNGLGLOBALALPHAFACTORUBSUNPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


