// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLFINISHFENCENVPROC {

    void apply(int x0);
    static MemoryAddress allocate(PFNGLFINISHFENCENVPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLFINISHFENCENVPROC.class, fi, constants$748.PFNGLFINISHFENCENVPROC$FUNC, "(I)V");
    }
    static MemoryAddress allocate(PFNGLFINISHFENCENVPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLFINISHFENCENVPROC.class, fi, constants$748.PFNGLFINISHFENCENVPROC$FUNC, "(I)V", scope);
    }
    static PFNGLFINISHFENCENVPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$748.PFNGLFINISHFENCENVPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


