// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLPOLYGONOFFSETEXTPROC {

    void apply(float x0, float x1);
    static MemoryAddress allocate(PFNGLPOLYGONOFFSETEXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLPOLYGONOFFSETEXTPROC.class, fi, constants$653.PFNGLPOLYGONOFFSETEXTPROC$FUNC, "(FF)V");
    }
    static MemoryAddress allocate(PFNGLPOLYGONOFFSETEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLPOLYGONOFFSETEXTPROC.class, fi, constants$653.PFNGLPOLYGONOFFSETEXTPROC$FUNC, "(FF)V", scope);
    }
    static PFNGLPOLYGONOFFSETEXTPROC ofAddress(MemoryAddress addr) {
        return (float x0, float x1) -> {
            try {
                constants$653.PFNGLPOLYGONOFFSETEXTPROC$MH.invokeExact((Addressable)addr, x0, x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


