// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$739 {

    static final FunctionDescriptor PFNGLCONSERVATIVERASTERPARAMETERINVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCONSERVATIVERASTERPARAMETERINVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$739.PFNGLCONSERVATIVERASTERPARAMETERINVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYIMAGESUBDATANVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYIMAGESUBDATANVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIIIIIIIII)V",
        constants$739.PFNGLCOPYIMAGESUBDATANVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEPTHRANGEDNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLDEPTHRANGEDNVPROC$MH = RuntimeHelper.downcallHandle(
        "(DD)V",
        constants$739.PFNGLDEPTHRANGEDNVPROC$FUNC, false
    );
}


