// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$806 {

    static final FunctionDescriptor PFNGLPATHFOGGENNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLPATHFOGGENNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$806.PFNGLPATHFOGGENNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPATHCOLORGENIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPATHCOLORGENIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$806.PFNGLGETPATHCOLORGENIVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPATHCOLORGENFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPATHCOLORGENFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$806.PFNGLGETPATHCOLORGENFVNVPROC$FUNC, false
    );
}


