// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$697 {

    static final FunctionDescriptor PFNGLACQUIREKEYEDMUTEXWIN32EXTPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT,
        C_LONG,
        C_INT
    );
    static final MethodHandle PFNGLACQUIREKEYEDMUTEXWIN32EXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IJI)B",
        constants$697.PFNGLACQUIREKEYEDMUTEXWIN32EXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLRELEASEKEYEDMUTEXWIN32EXTPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLRELEASEKEYEDMUTEXWIN32EXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)B",
        constants$697.PFNGLRELEASEKEYEDMUTEXWIN32EXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLWINDOWRECTANGLESEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLWINDOWRECTANGLESEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$697.PFNGLWINDOWRECTANGLESEXTPROC$FUNC, false
    );
}


