// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$511 {

    static final FunctionDescriptor PFNGLVERTEXSTREAM4DVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXSTREAM4DVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$511.PFNGLVERTEXSTREAM4DVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMALSTREAM3BATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_CHAR,
        C_CHAR,
        C_CHAR
    );
    static final MethodHandle PFNGLNORMALSTREAM3BATIPROC$MH = RuntimeHelper.downcallHandle(
        "(IBBB)V",
        constants$511.PFNGLNORMALSTREAM3BATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMALSTREAM3BVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLNORMALSTREAM3BVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$511.PFNGLNORMALSTREAM3BVATIPROC$FUNC, false
    );
}


