// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$747 {

    static final FunctionDescriptor PFNGLDELETEFENCESNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDELETEFENCESNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$747.PFNGLDELETEFENCESNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGENFENCESNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGENFENCESNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$747.PFNGLGENFENCESNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISFENCENVPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT
    );
    static final MethodHandle PFNGLISFENCENVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)B",
        constants$747.PFNGLISFENCENVPROC$FUNC, false
    );
}


