// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$862 {

    static final FunctionDescriptor PFNGLVERTEXATTRIB3DNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLVERTEXATTRIB3DNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IDDD)V",
        constants$862.PFNGLVERTEXATTRIB3DNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3DVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIB3DVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$862.PFNGLVERTEXATTRIB3DVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIB3FNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLVERTEXATTRIB3FNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IFFF)V",
        constants$862.PFNGLVERTEXATTRIB3FNVPROC$FUNC, false
    );
}


