// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$337 {

    static final FunctionDescriptor PFNGLGETNUNIFORMI64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETNUNIFORMI64VARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$337.PFNGLGETNUNIFORMI64VARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETNUNIFORMUI64VARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETNUNIFORMUI64VARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$337.PFNGLGETNUNIFORMUI64VARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMUNIFORM1I64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLPROGRAMUNIFORM1I64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJ)V",
        constants$337.PFNGLPROGRAMUNIFORM1I64ARBPROC$FUNC, false
    );
}


