// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$500 {

    static final FunctionDescriptor PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$500.PFNGLGETVERTEXATTRIBARRAYOBJECTFVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$500.PFNGLGETVERTEXATTRIBARRAYOBJECTIVATIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXSTREAM1SATIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_SHORT
    );
    static final MethodHandle PFNGLVERTEXSTREAM1SATIPROC$MH = RuntimeHelper.downcallHandle(
        "(IS)V",
        constants$500.PFNGLVERTEXSTREAM1SATIPROC$FUNC, false
    );
}


