// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$888 {

    static final FunctionDescriptor PFNGLPOINTPARAMETERFVSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPOINTPARAMETERFVSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$888.PFNGLPOINTPARAMETERFVSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSHARPENTEXFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLSHARPENTEXFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$888.PFNGLSHARPENTEXFUNCSGISPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETSHARPENTEXFUNCSGISPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETSHARPENTEXFUNCSGISPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$888.PFNGLGETSHARPENTEXFUNCSGISPROC$FUNC, false
    );
}


