// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$664 {

    static final FunctionDescriptor PFNGLACTIVEPROGRAMEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLACTIVEPROGRAMEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$664.PFNGLACTIVEPROGRAMEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCREATESHADERPROGRAMEXTPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCREATESHADERPROGRAMEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$664.PFNGLCREATESHADERPROGRAMEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFRAMEBUFFERFETCHBARRIEREXTPROC$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle PFNGLFRAMEBUFFERFETCHBARRIEREXTPROC$MH = RuntimeHelper.downcallHandle(
        "()V",
        constants$664.PFNGLFRAMEBUFFERFETCHBARRIEREXTPROC$FUNC, false
    );
}


