// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$623 {

    static final FunctionDescriptor PFNGLFOGCOORDFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT
    );
    static final MethodHandle PFNGLFOGCOORDFEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(F)V",
        constants$623.PFNGLFOGCOORDFEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGCOORDFVEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLFOGCOORDFVEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$623.PFNGLFOGCOORDFVEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGCOORDDEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE
    );
    static final MethodHandle PFNGLFOGCOORDDEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(D)V",
        constants$623.PFNGLFOGCOORDDEXTPROC$FUNC, false
    );
}


