// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$603 {

    static final FunctionDescriptor PFNGLVERTEXARRAYNORMALOFFSETEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXARRAYNORMALOFFSETEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIJ)V",
        constants$603.PFNGLVERTEXARRAYNORMALOFFSETEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXARRAYTEXCOORDOFFSETEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXARRAYTEXCOORDOFFSETEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIJ)V",
        constants$603.PFNGLVERTEXARRAYTEXCOORDOFFSETEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXARRAYMULTITEXCOORDOFFSETEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXARRAYMULTITEXCOORDOFFSETEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIJ)V",
        constants$603.PFNGLVERTEXARRAYMULTITEXCOORDOFFSETEXTPROC$FUNC, false
    );
}


