// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$344 {

    static final FunctionDescriptor PFNGLCURRENTPALETTEMATRIXARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLCURRENTPALETTEMATRIXARBPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$344.PFNGLCURRENTPALETTEMATRIXARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXINDEXUBVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMATRIXINDEXUBVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$344.PFNGLMATRIXINDEXUBVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXINDEXUSVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMATRIXINDEXUSVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$344.PFNGLMATRIXINDEXUSVARBPROC$FUNC, false
    );
}


