// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$908 {

    static final FunctionDescriptor PFNGLCOLORTABLEPARAMETERIVSGIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOLORTABLEPARAMETERIVSGIPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$908.PFNGLCOLORTABLEPARAMETERIVSGIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYCOLORTABLESGIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYCOLORTABLESGIPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$908.PFNGLCOPYCOLORTABLESGIPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOLORTABLESGIPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETCOLORTABLESGIPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$908.PFNGLGETCOLORTABLESGIPROC$FUNC, false
    );
}


