// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$839 {

    static final FunctionDescriptor PFNGLVERTEXARRAYRANGENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXARRAYRANGENVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$839.PFNGLVERTEXARRAYRANGENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL1I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL1I64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)V",
        constants$839.PFNGLVERTEXATTRIBL1I64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL2I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLVERTEXATTRIBL2I64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$839.PFNGLVERTEXATTRIBL2I64NVPROC$FUNC, false
    );
}


