// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$443 {

    static final FunctionDescriptor PFNGLTEXCOORD1XVOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLTEXCOORD1XVOESPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$443.PFNGLTEXCOORD1XVOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXCOORD2XOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXCOORD2XOESPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$443.PFNGLTEXCOORD2XOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXCOORD2XVOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLTEXCOORD2XVOESPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$443.PFNGLTEXCOORD2XVOESPROC$FUNC, false
    );
}


