// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$899 {

    static final FunctionDescriptor PFNGLFRAMEZOOMSGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLFRAMEZOOMSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$899.PFNGLFRAMEZOOMSGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLIGLOOINTERFACESGIXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLIGLOOINTERFACESGIXPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$899.PFNGLIGLOOINTERFACESGIXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETINSTRUMENTSSGIXPROC$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle PFNGLGETINSTRUMENTSSGIXPROC$MH = RuntimeHelper.downcallHandle(
        "()I",
        constants$899.PFNGLGETINSTRUMENTSSGIXPROC$FUNC, false
    );
}


