// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$939 {

    static final FunctionDescriptor gluTessEndPolygon$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle gluTessEndPolygon$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluTessEndPolygon",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$939.gluTessEndPolygon$FUNC, false
    );
    static final FunctionDescriptor gluTessNormal$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle gluTessNormal$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluTessNormal",
        "(Ljdk/incubator/foreign/MemoryAddress;DDD)V",
        constants$939.gluTessNormal$FUNC, false
    );
    static final FunctionDescriptor gluTessProperty$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_DOUBLE
    );
    static final MethodHandle gluTessProperty$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluTessProperty",
        "(Ljdk/incubator/foreign/MemoryAddress;ID)V",
        constants$939.gluTessProperty$FUNC, false
    );
    static final FunctionDescriptor gluTessVertex$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluTessVertex$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluTessVertex",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$939.gluTessVertex$FUNC, false
    );
    static final FunctionDescriptor gluUnProject$FUNC = FunctionDescriptor.of(C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluUnProject$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluUnProject",
        "(DDDLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$939.gluUnProject$FUNC, false
    );
    static final FunctionDescriptor gluUnProject4$FUNC = FunctionDescriptor.of(C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_DOUBLE,
        C_DOUBLE,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle gluUnProject4$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "gluUnProject4",
        "(DDDDLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;DDLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$939.gluUnProject4$FUNC, false
    );
}


