// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$331 {

    static final FunctionDescriptor PFNGLUNIFORM1I64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM1I64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)V",
        constants$331.PFNGLUNIFORM1I64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM2I64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM2I64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$331.PFNGLUNIFORM2I64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM3I64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM3I64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJ)V",
        constants$331.PFNGLUNIFORM3I64ARBPROC$FUNC, false
    );
}


