// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$484 {

    static final FunctionDescriptor PFNGLENABLEVERTEXATTRIBAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLENABLEVERTEXATTRIBAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$484.PFNGLENABLEVERTEXATTRIBAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDISABLEVERTEXATTRIBAPPLEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDISABLEVERTEXATTRIBAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$484.PFNGLDISABLEVERTEXATTRIBAPPLEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLISVERTEXATTRIBENABLEDAPPLEPROC$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLISVERTEXATTRIBENABLEDAPPLEPROC$MH = RuntimeHelper.downcallHandle(
        "(II)B",
        constants$484.PFNGLISVERTEXATTRIBENABLEDAPPLEPROC$FUNC, false
    );
}


