// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$276 {

    static final FunctionDescriptor PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$276.PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETNAMEDBUFFERPARAMETERIVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETNAMEDBUFFERPARAMETERIVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$276.PFNGLGETNAMEDBUFFERPARAMETERIVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETNAMEDBUFFERPARAMETERI64VPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETNAMEDBUFFERPARAMETERI64VPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$276.PFNGLGETNAMEDBUFFERPARAMETERI64VPROC$FUNC, false
    );
}


