// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$248 {

    static final FunctionDescriptor PFNGLGETFLOATI_VPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETFLOATI_VPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$248.PFNGLGETFLOATI_VPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETDOUBLEI_VPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETDOUBLEI_VPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$248.PFNGLGETDOUBLEI_VPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$248.PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC$FUNC, false
    );
}


