// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$737 {

    static final FunctionDescriptor PFNGLCOMPILECOMMANDLISTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLCOMPILECOMMANDLISTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$737.PFNGLCOMPILECOMMANDLISTNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCALLCOMMANDLISTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLCALLCOMMANDLISTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$737.PFNGLCALLCOMMANDLISTNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBEGINCONDITIONALRENDERNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLBEGINCONDITIONALRENDERNVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)V",
        constants$737.PFNGLBEGINCONDITIONALRENDERNVPROC$FUNC, false
    );
}


