// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$648 {

    static final FunctionDescriptor PFNGLMULTIDRAWARRAYSEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle PFNGLMULTIDRAWARRAYSEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$648.PFNGLMULTIDRAWARRAYSEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTIDRAWELEMENTSEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle PFNGLMULTIDRAWELEMENTSEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)V",
        constants$648.PFNGLMULTIDRAWELEMENTSEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSAMPLEMASKEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_CHAR
    );
    static final MethodHandle PFNGLSAMPLEMASKEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(FB)V",
        constants$648.PFNGLSAMPLEMASKEXTPROC$FUNC, false
    );
}


