// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$950 {

    static final FunctionDescriptor glutIdleFunc$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glutIdleFunc$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glutIdleFunc",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$950.glutIdleFunc$FUNC, false
    );
    static final FunctionDescriptor glutKeyboardFunc$callback$FUNC = FunctionDescriptor.ofVoid(
        C_CHAR,
        C_INT,
        C_INT
    );
    static final MethodHandle glutKeyboardFunc$callback$MH = RuntimeHelper.downcallHandle(
        "(BII)V",
        constants$950.glutKeyboardFunc$callback$FUNC, false
    );
    static final FunctionDescriptor glutKeyboardFunc$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glutKeyboardFunc$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glutKeyboardFunc",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$950.glutKeyboardFunc$FUNC, false
    );
    static final FunctionDescriptor glutSpecialFunc$callback$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle glutSpecialFunc$callback$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$950.glutSpecialFunc$callback$FUNC, false
    );
}


