// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$773 {

    static final FunctionDescriptor PFNGLMULTITEXCOORD4HVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMULTITEXCOORD4HVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$773.PFNGLMULTITEXCOORD4HVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGCOORDHNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT
    );
    static final MethodHandle PFNGLFOGCOORDHNVPROC$MH = RuntimeHelper.downcallHandle(
        "(S)V",
        constants$773.PFNGLFOGCOORDHNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLFOGCOORDHVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle PFNGLFOGCOORDHVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$773.PFNGLFOGCOORDHVNVPROC$FUNC, false
    );
}


