// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$328 {

    static final FunctionDescriptor PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$328.PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMIVARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPROGRAMIVARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$328.PFNGLGETPROGRAMIVARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETPROGRAMSTRINGARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETPROGRAMSTRINGARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$328.PFNGLGETPROGRAMSTRINGARBPROC$FUNC, false
    );
}


