// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$721 {

    static final FunctionDescriptor PFNGLMULTICASTVIEWPORTARRAYVNVXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMULTICASTVIEWPORTARRAYVNVXPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$721.PFNGLMULTICASTVIEWPORTARRAYVNVXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTICASTVIEWPORTPOSITIONWSCALENVXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLMULTICASTVIEWPORTPOSITIONWSCALENVXPROC$MH = RuntimeHelper.downcallHandle(
        "(IIFF)V",
        constants$721.PFNGLMULTICASTVIEWPORTPOSITIONWSCALENVXPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMULTICASTSCISSORARRAYVNVXPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLMULTICASTSCISSORARRAYVNVXPROC$MH = RuntimeHelper.downcallHandle(
        "(IIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$721.PFNGLMULTICASTSCISSORARRAYVNVXPROC$FUNC, false
    );
}


