// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$911 {

    static final FunctionDescriptor PFNGLGLOBALALPHAFACTORFSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT
    );
    static final MethodHandle PFNGLGLOBALALPHAFACTORFSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(F)V",
        constants$911.PFNGLGLOBALALPHAFACTORFSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGLOBALALPHAFACTORDSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE
    );
    static final MethodHandle PFNGLGLOBALALPHAFACTORDSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(D)V",
        constants$911.PFNGLGLOBALALPHAFACTORDSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGLOBALALPHAFACTORUBSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_CHAR
    );
    static final MethodHandle PFNGLGLOBALALPHAFACTORUBSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(B)V",
        constants$911.PFNGLGLOBALALPHAFACTORUBSUNPROC$FUNC, false
    );
}


