// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$458 {

    static final FunctionDescriptor PFNGLUNIFORM4I64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLUNIFORM4I64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$458.PFNGLUNIFORM4I64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM1UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM1UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJ)V",
        constants$458.PFNGLUNIFORM1UI64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM2UI64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM2UI64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$458.PFNGLUNIFORM2UI64NVPROC$FUNC, false
    );
}


