// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$334 {

    static final FunctionDescriptor PFNGLUNIFORM2UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM2UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$334.PFNGLUNIFORM2UI64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM3UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM3UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJ)V",
        constants$334.PFNGLUNIFORM3UI64ARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM4UI64ARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM4UI64ARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJJ)V",
        constants$334.PFNGLUNIFORM4UI64ARBPROC$FUNC, false
    );
}


