// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$845 {

    static final FunctionDescriptor PFNGLGETVERTEXATTRIBLUI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBLUI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$845.PFNGLGETVERTEXATTRIBLUI64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBLFORMATNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLVERTEXATTRIBLFORMATNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$845.PFNGLVERTEXATTRIBLFORMATNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBUFFERADDRESSRANGENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLBUFFERADDRESSRANGENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJJ)V",
        constants$845.PFNGLBUFFERADDRESSRANGENVPROC$FUNC, false
    );
}


