// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$538 {

    static final FunctionDescriptor PFNGLMATRIXROTATEDEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLMATRIXROTATEDEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IDDDD)V",
        constants$538.PFNGLMATRIXROTATEDEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXSCALEFEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLMATRIXSCALEFEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IFFF)V",
        constants$538.PFNGLMATRIXSCALEFEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMATRIXSCALEDEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_DOUBLE,
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLMATRIXSCALEDEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IDDD)V",
        constants$538.PFNGLMATRIXSCALEDEXTPROC$FUNC, false
    );
}


