// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$740 {

    static final FunctionDescriptor PFNGLCLEARDEPTHDNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE
    );
    static final MethodHandle PFNGLCLEARDEPTHDNVPROC$MH = RuntimeHelper.downcallHandle(
        "(D)V",
        constants$740.PFNGLCLEARDEPTHDNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEPTHBOUNDSDNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE,
        C_DOUBLE
    );
    static final MethodHandle PFNGLDEPTHBOUNDSDNVPROC$MH = RuntimeHelper.downcallHandle(
        "(DD)V",
        constants$740.PFNGLDEPTHBOUNDSDNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDRAWTEXTURENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLDRAWTEXTURENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIFFFFFFFFF)V",
        constants$740.PFNGLDRAWTEXTURENVPROC$FUNC, false
    );
}


