// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$421 {

    static final FunctionDescriptor PFNGLMULTITEXCOORD4XOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLMULTITEXCOORD4XOESPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$421.PFNGLMULTITEXCOORD4XOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLNORMAL3XOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLNORMAL3XOESPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$421.PFNGLNORMAL3XOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLORTHOXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLORTHOXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIII)V",
        constants$421.PFNGLORTHOXOESPROC$FUNC, false
    );
}


