// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$913 {

    static final FunctionDescriptor PFNGLREPLACEMENTCODEUISUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUISUNPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$913.PFNGLREPLACEMENTCODEUISUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLREPLACEMENTCODEUSSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_SHORT
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUSSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(S)V",
        constants$913.PFNGLREPLACEMENTCODEUSSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLREPLACEMENTCODEUBSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_CHAR
    );
    static final MethodHandle PFNGLREPLACEMENTCODEUBSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(B)V",
        constants$913.PFNGLREPLACEMENTCODEUBSUNPROC$FUNC, false
    );
}


