// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$319 {

    static final FunctionDescriptor GLDEBUGPROCARB$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle GLDEBUGPROCARB$MH = RuntimeHelper.downcallHandle(
        "(IIIIILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$319.GLDEBUGPROCARB$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEBUGMESSAGECONTROLARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER,
        C_CHAR
    );
    static final MethodHandle PFNGLDEBUGMESSAGECONTROLARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;B)V",
        constants$319.PFNGLDEBUGMESSAGECONTROLARBPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLDEBUGMESSAGEINSERTARBPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLDEBUGMESSAGEINSERTARBPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$319.PFNGLDEBUGMESSAGEINSERTARBPROC$FUNC, false
    );
}


