// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$456 {

    static final FunctionDescriptor PFNGLUNIFORM2I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM2I64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJ)V",
        constants$456.PFNGLUNIFORM2I64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM3I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM3I64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJ)V",
        constants$456.PFNGLUNIFORM3I64NVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLUNIFORM4I64NVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle PFNGLUNIFORM4I64NVPROC$MH = RuntimeHelper.downcallHandle(
        "(IJJJJ)V",
        constants$456.PFNGLUNIFORM4I64NVPROC$FUNC, false
    );
}


