// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$423 {

    static final FunctionDescriptor PFNGLROTATEXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLROTATEXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(IIII)V",
        constants$423.PFNGLROTATEXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLSCALEXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLSCALEXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$423.PFNGLSCALEXOESPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXENVXOESPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLTEXENVXOESPROC$MH = RuntimeHelper.downcallHandle(
        "(III)V",
        constants$423.PFNGLTEXENVXOESPROC$FUNC, false
    );
}


