// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$813 {

    static final FunctionDescriptor PFNGLCOMBINERPARAMETERFVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOMBINERPARAMETERFVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$813.PFNGLCOMBINERPARAMETERFVNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOMBINERPARAMETERFNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLCOMBINERPARAMETERFNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IF)V",
        constants$813.PFNGLCOMBINERPARAMETERFNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOMBINERPARAMETERIVNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLCOMBINERPARAMETERIVNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$813.PFNGLCOMBINERPARAMETERIVNVPROC$FUNC, false
    );
}


