// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$644 {

    static final FunctionDescriptor PFNGLTEXSTORAGEMEM3DMULTISAMPLEEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_CHAR,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLTEXSTORAGEMEM3DMULTISAMPLEEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIBIJ)V",
        constants$644.PFNGLTEXSTORAGEMEM3DMULTISAMPLEEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBUFFERSTORAGEMEMEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_LONG,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLBUFFERSTORAGEMEMEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IJIJ)V",
        constants$644.PFNGLBUFFERSTORAGEMEMEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLTEXTURESTORAGEMEM2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLTEXTURESTORAGEMEM2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIJ)V",
        constants$644.PFNGLTEXTURESTORAGEMEM2DEXTPROC$FUNC, false
    );
}


