// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$727 {

    static final FunctionDescriptor PFNGLGETTEXTURESAMPLERHANDLENVPROC$FUNC = FunctionDescriptor.of(C_LONG,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLGETTEXTURESAMPLERHANDLENVPROC$MH = RuntimeHelper.downcallHandle(
        "(II)J",
        constants$727.PFNGLGETTEXTURESAMPLERHANDLENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMAKETEXTUREHANDLERESIDENTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_LONG
    );
    static final MethodHandle PFNGLMAKETEXTUREHANDLERESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(J)V",
        constants$727.PFNGLMAKETEXTUREHANDLERESIDENTNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLMAKETEXTUREHANDLENONRESIDENTNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_LONG
    );
    static final MethodHandle PFNGLMAKETEXTUREHANDLENONRESIDENTNVPROC$MH = RuntimeHelper.downcallHandle(
        "(J)V",
        constants$727.PFNGLMAKETEXTUREHANDLENONRESIDENTNVPROC$FUNC, false
    );
}


