// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$804 {

    static final FunctionDescriptor PFNGLPATHGLYPHINDEXARRAYNVPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_INT,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLPATHGLYPHINDEXARRAYNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;IIIIF)I",
        constants$804.PFNGLPATHGLYPHINDEXARRAYNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPATHMEMORYGLYPHINDEXARRAYNVPROC$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_INT,
        C_LONG,
        C_POINTER,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_FLOAT
    );
    static final MethodHandle PFNGLPATHMEMORYGLYPHINDEXARRAYNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIJLjdk/incubator/foreign/MemoryAddress;IIIIF)I",
        constants$804.PFNGLPATHMEMORYGLYPHINDEXARRAYNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLPROGRAMPATHFRAGMENTINPUTGENNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLPROGRAMPATHFRAGMENTINPUTGENNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$804.PFNGLPROGRAMPATHFRAGMENTINPUTGENNVPROC$FUNC, false
    );
}


