// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$544 {

    static final FunctionDescriptor PFNGLTEXTURESUBIMAGE2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLTEXTURESUBIMAGE2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$544.PFNGLTEXTURESUBIMAGE2DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYTEXTUREIMAGE1DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYTEXTUREIMAGE1DEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIII)V",
        constants$544.PFNGLCOPYTEXTUREIMAGE1DEXTPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOPYTEXTUREIMAGE2DEXTPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLCOPYTEXTUREIMAGE2DEXTPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIII)V",
        constants$544.PFNGLCOPYTEXTUREIMAGE2DEXTPROC$FUNC, false
    );
}


