// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$844 {

    static final FunctionDescriptor PFNGLVERTEXATTRIBL3UI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIBL3UI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$844.PFNGLVERTEXATTRIBL3UI64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLVERTEXATTRIBL4UI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLVERTEXATTRIBL4UI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$844.PFNGLVERTEXATTRIBL4UI64VNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETVERTEXATTRIBLI64VNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETVERTEXATTRIBLI64VNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$844.PFNGLGETVERTEXATTRIBLI64VNVPROC$FUNC, false
    );
}


