// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$879 {

    static final FunctionDescriptor PFNGLBINDVIDEOCAPTURESTREAMBUFFERNVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_LONG
    );
    static final MethodHandle PFNGLBINDVIDEOCAPTURESTREAMBUFFERNVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIJ)V",
        constants$879.PFNGLBINDVIDEOCAPTURESTREAMBUFFERNVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLBINDVIDEOCAPTURESTREAMTEXTURENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT
    );
    static final MethodHandle PFNGLBINDVIDEOCAPTURESTREAMTEXTURENVPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIII)V",
        constants$879.PFNGLBINDVIDEOCAPTURESTREAMTEXTURENVPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLENDVIDEOCAPTURENVPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLENDVIDEOCAPTURENVPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$879.PFNGLENDVIDEOCAPTURENVPROC$FUNC, false
    );
}


