// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$303 {

    static final FunctionDescriptor PFNGLMEMORYBARRIERBYREGIONPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT
    );
    static final MethodHandle PFNGLMEMORYBARRIERBYREGIONPROC$MH = RuntimeHelper.downcallHandle(
        "(I)V",
        constants$303.PFNGLMEMORYBARRIERBYREGIONPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETTEXTURESUBIMAGEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETTEXTURESUBIMAGEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$303.PFNGLGETTEXTURESUBIMAGEPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC$MH = RuntimeHelper.downcallHandle(
        "(IIIIIIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$303.PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC$FUNC, false
    );
}


