// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$916 {

    static final FunctionDescriptor PFNGLCOLOR4UBVERTEX3FSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_CHAR,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLCOLOR4UBVERTEX3FSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(BBBBFFF)V",
        constants$916.PFNGLCOLOR4UBVERTEX3FSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLOR4UBVERTEX3FVSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle PFNGLCOLOR4UBVERTEX3FVSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$916.PFNGLCOLOR4UBVERTEX3FVSUNPROC$FUNC, false
    );
    static final FunctionDescriptor PFNGLCOLOR3FVERTEX3FSUNPROC$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT,
        C_FLOAT
    );
    static final MethodHandle PFNGLCOLOR3FVERTEX3FSUNPROC$MH = RuntimeHelper.downcallHandle(
        "(FFFFFF)V",
        constants$916.PFNGLCOLOR3FVERTEX3FSUNPROC$FUNC, false
    );
}


