// Generated by jextract

package opengl.ubuntu.v20;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface PFNGLAPPLYTEXTUREEXTPROC {

    void apply(int x0);
    static MemoryAddress allocate(PFNGLAPPLYTEXTUREEXTPROC fi) {
        return RuntimeHelper.upcallStub(PFNGLAPPLYTEXTUREEXTPROC.class, fi, constants$639.PFNGLAPPLYTEXTUREEXTPROC$FUNC, "(I)V");
    }
    static MemoryAddress allocate(PFNGLAPPLYTEXTUREEXTPROC fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(PFNGLAPPLYTEXTUREEXTPROC.class, fi, constants$639.PFNGLAPPLYTEXTUREEXTPROC$FUNC, "(I)V", scope);
    }
    static PFNGLAPPLYTEXTUREEXTPROC ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$639.PFNGLAPPLYTEXTUREEXTPROC$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


