// Generated by jextract

package opengl.macos.v11_4;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$19 {

    static final FunctionDescriptor glFenceSync$FUNC = FunctionDescriptor.of(C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle glFenceSync$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glFenceSync",
        "(II)Ljdk/incubator/foreign/MemoryAddress;",
        constants$19.glFenceSync$FUNC, false
    );
    static final FunctionDescriptor glIsSync$FUNC = FunctionDescriptor.of(C_CHAR,
        C_POINTER
    );
    static final MethodHandle glIsSync$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIsSync",
        "(Ljdk/incubator/foreign/MemoryAddress;)B",
        constants$19.glIsSync$FUNC, false
    );
    static final FunctionDescriptor glDeleteSync$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glDeleteSync$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glDeleteSync",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$19.glDeleteSync$FUNC, false
    );
    static final FunctionDescriptor glClientWaitSync$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_LONG_LONG
    );
    static final MethodHandle glClientWaitSync$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glClientWaitSync",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)I",
        constants$19.glClientWaitSync$FUNC, false
    );
    static final FunctionDescriptor glWaitSync$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_LONG_LONG
    );
    static final MethodHandle glWaitSync$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glWaitSync",
        "(Ljdk/incubator/foreign/MemoryAddress;IJ)V",
        constants$19.glWaitSync$FUNC, false
    );
    static final FunctionDescriptor glGetInteger64v$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetInteger64v$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetInteger64v",
        "(ILjdk/incubator/foreign/MemoryAddress;)V",
        constants$19.glGetInteger64v$FUNC, false
    );
}


