// Generated by jextract

package opengl.macos.v11_4;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$52 {

    static final FunctionDescriptor glUniform4uivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glUniform4uivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniform4uivEXT",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$52.glUniform4uivEXT$FUNC, false
    );
    static final FunctionDescriptor glGetUniformuivEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetUniformuivEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetUniformuivEXT",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$52.glGetUniformuivEXT$FUNC, false
    );
    static final FunctionDescriptor glBindFragDataLocationEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glBindFragDataLocationEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glBindFragDataLocationEXT",
        "(IILjdk/incubator/foreign/MemoryAddress;)V",
        constants$52.glBindFragDataLocationEXT$FUNC, false
    );
    static final FunctionDescriptor glGetFragDataLocationEXT$FUNC = FunctionDescriptor.of(C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glGetFragDataLocationEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glGetFragDataLocationEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$52.glGetFragDataLocationEXT$FUNC, false
    );
    static final FunctionDescriptor glMultiDrawArraysEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle glMultiDrawArraysEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiDrawArraysEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)V",
        constants$52.glMultiDrawArraysEXT$FUNC, false
    );
    static final FunctionDescriptor glMultiDrawElementsEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle glMultiDrawElementsEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glMultiDrawElementsEXT",
        "(ILjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)V",
        constants$52.glMultiDrawElementsEXT$FUNC, false
    );
}


