// Generated by jextract

package opengl.macos.v11_4;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$42 {

    static final FunctionDescriptor glIsEnabledIndexedEXT$FUNC = FunctionDescriptor.of(C_CHAR,
        C_INT,
        C_INT
    );
    static final MethodHandle glIsEnabledIndexedEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glIsEnabledIndexedEXT",
        "(II)B",
        constants$42.glIsEnabledIndexedEXT$FUNC, false
    );
    static final FunctionDescriptor glDrawRangeElementsEXT$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_INT,
        C_POINTER
    );
    static final MethodHandle glDrawRangeElementsEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glDrawRangeElementsEXT",
        "(IIIIILjdk/incubator/foreign/MemoryAddress;)V",
        constants$42.glDrawRangeElementsEXT$FUNC, false
    );
    static final FunctionDescriptor glFogCoordfEXT$FUNC = FunctionDescriptor.ofVoid(
        C_FLOAT
    );
    static final MethodHandle glFogCoordfEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glFogCoordfEXT",
        "(F)V",
        constants$42.glFogCoordfEXT$FUNC, false
    );
    static final FunctionDescriptor glFogCoordfvEXT$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glFogCoordfvEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glFogCoordfvEXT",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$42.glFogCoordfvEXT$FUNC, false
    );
    static final FunctionDescriptor glFogCoorddEXT$FUNC = FunctionDescriptor.ofVoid(
        C_DOUBLE
    );
    static final MethodHandle glFogCoorddEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glFogCoorddEXT",
        "(D)V",
        constants$42.glFogCoorddEXT$FUNC, false
    );
    static final FunctionDescriptor glFogCoorddvEXT$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle glFogCoorddvEXT$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glFogCoorddvEXT",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$42.glFogCoorddvEXT$FUNC, false
    );
}


