// Generated by jextract

package opengl.macos.v11_4;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$163 {

    static final FunctionDescriptor glUniformMatrix2x3fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix2x3fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix2x3fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix2x3fv$FUNC, false
    );
    static final FunctionDescriptor glUniformMatrix3x2fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix3x2fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix3x2fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix3x2fv$FUNC, false
    );
    static final FunctionDescriptor glUniformMatrix2x4fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix2x4fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix2x4fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix2x4fv$FUNC, false
    );
    static final FunctionDescriptor glUniformMatrix4x2fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix4x2fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix4x2fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix4x2fv$FUNC, false
    );
    static final FunctionDescriptor glUniformMatrix3x4fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix3x4fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix3x4fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix3x4fv$FUNC, false
    );
    static final FunctionDescriptor glUniformMatrix4x3fv$FUNC = FunctionDescriptor.ofVoid(
        C_INT,
        C_INT,
        C_CHAR,
        C_POINTER
    );
    static final MethodHandle glUniformMatrix4x3fv$MH = RuntimeHelper.downcallHandle(
        glut_h.LIBRARIES, "glUniformMatrix4x3fv",
        "(IIBLjdk/incubator/foreign/MemoryAddress;)V",
        constants$163.glUniformMatrix4x3fv$FUNC, false
    );
}


