// Generated by jextract

package opengl.macos.v11_4;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface glutWindowStatusFunc$func {

    void apply(int x0);
    static MemoryAddress allocate(glutWindowStatusFunc$func fi) {
        return RuntimeHelper.upcallStub(glutWindowStatusFunc$func.class, fi, constants$195.glutWindowStatusFunc$func$FUNC, "(I)V");
    }
    static MemoryAddress allocate(glutWindowStatusFunc$func fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(glutWindowStatusFunc$func.class, fi, constants$195.glutWindowStatusFunc$func$FUNC, "(I)V", scope);
    }
    static glutWindowStatusFunc$func ofAddress(MemoryAddress addr) {
        return (int x0) -> {
            try {
                constants$195.glutWindowStatusFunc$func$MH.invokeExact((Addressable)addr, x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


